VEuPathDB/web-monorepo

README.adoc
package.json

The version of node listed in the readme is incorrect. This PR fixes that, and also sets the `engines` and `volta` fields.

update readme and package.json with correct version of node

---

packages/libs/eda/src/lib/map/analysis/FloatingVisualization.tsx
packages/libs/eda/src/lib/map/analysis/FloatingVizManagement.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx

I think this is probably the way to go. Reverses a lot of what I did the other day...
The alternative is to have all menu tabs rendered all the time (but not necessarily visible). I'm a bit uneasy about that.

Move floating viz "activeViz" to parent outside of `FloatingVizManagement`

---

.github/workflows/npm-publish-sites.yml
nx.json
packages/sites/clinepi-site/package.json
packages/sites/genomics-site/package.json
packages/sites/mbio-site/package.json
packages/sites/ortho-site/package.json

This PR adds a workflow for publishing npm packages for sites. The workflow will only run when commits are pushed to `main` and changes are made to sites package.json. 
I also cleaned up dependencies in sites package.json so that consumers of the sites npm packages only install the generated bundles.

GitHub action publish

---

packages/libs/components/src/plots/Histogram.tsx
packages/libs/eda/src/lib/core/components/filter/HistogramFilter.tsx

This will resolve https://github.com/VEuPathDB/web-eda/issues/1677 (stats) and https://github.com/VEuPathDB/EdaNewIssues/issues/603 (plot). Currently significant figures are set to be 5.
A screenshot is attached here (same example used at https://github.com/VEuPathDB/web-eda/issues/1677#issuecomment-1454240302 is utilized here for a better comparison):

introducing scientific notation for histogram stats and plot

---

packages/libs/eda/src/lib/workspace/EDAWorkspace.scss
packages/sites/clinepi-site/webapp/css/ClinEpiSite.scss
packages/sites/mbio-site/webapp/css/MicrobiomeSite.css

Resolves https://github.com/VEuPathDB/web-eda/issues/1621
I tested in both Mbio and ClinEpi sites. Screenshots below.
Note to reviewer: since `web-eda` dev server doesn't have the sticky site header, I didn't account for it. This is another instance in which the dev environment deviates from the final styling, which can lead to errors like this. I will open an issue that will articulate the need to "sync up" the styles applied in our dev environments and/or create an SOP for how we should be testing changes more robustly.

Account for site headers' vertical height in EDAWorkspaceNavigation

---

packages/libs/coreui/src/components/inputs/SearchBox/SearchBox.tsx
packages/libs/preferred-organisms/src/lib/components/PreferredOrganismsConfig.tsx
packages/libs/web-common/src/components/SiteSearch/SiteSearch.tsx
packages/libs/web-common/src/components/homepage/SearchPane.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/OrganismFilter.tsx

Recent updates to UPenn Macs surfaced an issue in Safari with the icon placement breaking in the `SearchBox` component. A bit of searching revealed that Safari has historically had issues with `position: absolute`. Also worth noting: the misaligned icon actually interferes with the functionality by blocking the "expand" toggle for the top-most item in the tree (`Haemoproteidae` in this case).
I initially used `position: absolute` as a wrapper with no height or width so that I could remove its contents from the document flow and then use `position: relative` on the icon itself. This was working fine cross-browser until this latest update.
I've removed the `position: absolute` wrapper. Instead, I added a "do nothing" `transform: rotate(0)` to the icon's parent container (`<label>`) and …

Fix broken SearchBox icon placement in Safari

---

packages/libs/multi-blast/src/lib/components/BlastWorkspaceResult.tsx
packages/libs/wdk-client/src/Views/Strategy/StepDetails.tsx

Resolves https://redmine.apidb.org/issues/50314
Implemented a `CollapsibleSection` so users can control the wall of text that can be shown. The "cutoff" has been arbitrarily set at 500 characters.
Default view when page loads:
View when user clicks to "show more":
Similar logic/behavior was added to the `StepDetails`.

Use CollapsibleSection for large text displays in BLAST

---

packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx

**Before**:
**After**: 
**Note:** we might be interested in adjusting the styling of this notes component. Presently the text is lightly colored and a touch small.

Implement the Notes menu item in standalone map

---

packages/libs/eda/src/lib/workspace/DownloadTab/StudyCitation.tsx

Resolves https://github.com/VEuPathDB/web-eda/issues/1510
After more prototyping, [we agreed that option 2 (no styling, no space)](https://github.com/VEuPathDB/web-eda/issues/1510#issuecomment-1508624152) was the best option for now. The screenshot below reflects these changes.

Remove italics from citation

---

packages/libs/web-common/src/styles/default-layout.scss

Resolves issue with question headers breaking when viewport width is below 1013px.
This screencast demonstrates the break:
https://user-images.githubusercontent.com/69446567/232842242-a85e3d8d-98e6-4bec-b87a-77a3d64550f5.mov
And this screencast demonstrates the small change:
https://user-images.githubusercontent.com/69446567/232842690-56e5b7b0-1117-4cd6-b6b0-b0719c7da7e4.mov

Adjust specificity for breakpoint within question form header

---

packages/libs/wdk-client/src/Core/Style/index.scss
packages/libs/wdk-client/src/Core/Style/jquery-ui-overrides.scss

Resolves https://redmine.apidb.org/issues/44206?project=true
Notice the "resize" indicators in the bottom right of the **Reference Samples** and **Comparison Samples** containers.

Add CSS to jquery-ui containers to indicate resizability

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
packages/libs/eda/src/lib/core/hooks/computeDefaultAxisRange.ts
packages/libs/eda/src/lib/core/utils/default-axis-range.ts

This PR branched out from the https://github.com/VEuPathDB/web-monorepo/tree/gradient-legend-suggestion (https://github.com/VEuPathDB/web-monorepo/pull/42) to update computation of the range. In addition, some reorganizations are made.
@bobular, can you please check this out? That normalize part may be out of data part as well but I just leave it as is because of the condition to run it, which requires backend response to check. This PR can be merged into your branch or main, but for now its destination is set to be your branch.

Computing range

---

packages/libs/components/src/components/plotControls/PlotListLegend.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Hi @chowington While I am reviewing your codes, I realized that you did (temporarily) block scatterplot's marker opacity part, perhaps because of the conflict with Lineplot's 0/0 case. Thus, I tried to activate both cases here. I don't know you already did similar stuff but wish this would be helpful for you 😃 
Just in case, this is branched out from your lineplot-zero-over-zero branch

add scatterplot marker opacity to legend

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

I noticed that the header menu item in genomics sites should point to the stand alone map. I aso noticed some missing provider components when a route is rendered fullscreen. This PR addresses those issues.

Update alpha map menu item, and add missing provider components.

---

packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.jsx
packages/libs/user-datasets/src/lib/Components/UserDatasetsWorkspace.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetListController.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetRouter.tsx
packages/libs/user-datasets/src/lib/Utils/types.ts
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/userDatasetRoutes.tsx
packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx

Resolves #98 
Related to https://github.com/VEuPathDB/EdaNewIssues/issues/621
**THE PROBLEM:** 
The `My User Studies` table in EDA (or `My Data Sets` in genomics) **currently** has disparate verbiage ("Datasets", "data sets", "Studies") as shown:
**THE SOLUTION:**
In introducing a `dataNoun` prop, we can specify singular and plural forms of the appropriate noun used in genomics or EDA sites.
This screenshot shows this new prop implemented in EDA:
This screenshot shows this new prop implemented in genomics:

Use new dataNoun prop in user dataset UI

---

packages/libs/coreui/src/components/buttons/index.ts
packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.scss
packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
packages/libs/user-datasets/src/lib/Components/ThemedDeleteButton.tsx
packages/libs/user-datasets/src/lib/Components/ThemedGrantAccessButton.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx

Resolves https://github.com/VEuPathDB/EdaNewIssues/issues/621 when combined with https://github.com/VEuPathDB/web-monorepo/pull/100
Replaced `Grant Access` and `Delete` buttons with `CoreUI` `MesaButton`s. The `Grant Access` button listens to the site's theme colors. The `Delete` button does not use theme colors but instead relies on style overrides to mimic the old look. Screenshots below.
**Mbio**:
**ClinEpi**:
**Plasmo**:

Theme user datasets buttons

---

packages/libs/coreui/tsconfig.json
packages/libs/wdk-client/src/StoreModules/QuestionStoreModule.ts
packages/libs/wdk-client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
packages/libs/wdk-client/src/Views/ResultTableSummaryView/Types.ts
packages/sites/genomics-site/.babelrc
packages/sites/genomics-site/.eslintrc
packages/sites/genomics-site/package.json
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/DownloadsFilter.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/DownloadsTable.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/index.ts
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/routes.jsx
yarn.lock

This PR implements the new download page for genomics sites.
fixes #29
This page makes use of two existing redux-based features: `QuestionController` and `ResultTableSummarViewController`. This new feature uses the redux state that `QuestionController` produces to derived a `ResultType` that can be passed to `ResultTableSummaryViewController`. We also take advantage of the ability to override some components' rendering to achieve the final result.
---
---
- **Checkout the branch:** `git co genomics-download-page`
- **Install dependencies:** `yarn install`
- **Create `packages/sites/genomics-site/.env`**, if necessary
- **Run the dev server:** `yarn nx start @veupathdb/genomics-site`

Implement new genomics download page

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx

This PR updates the primary color of the coreui theme for genomics sites. The color is meant to be as close to the link color as possible.
**Before**
**After**

Use a primary color close to current link colors

---

packages/libs/eda/src/lib/map/analysis/MapSideNavigation.tsx

**Before**:
Certain browsers + OSs will render scrollbars all the time. Scrollbars are a major accessibility concern and browser rendering engines and OSs disagree as to how and when they should be rendered.
**After**:
This PR removes needless `overflow: scroll`s thereby resolving this UI bug.

Ensure side navigation doesn't render multiple scrollbars constantly 

---

packages/libs/web-common/src/components/homepage/Header.scss

Trivial change to genomics site headers.
This is the only non-formatting change: https://github.com/VEuPathDB/web-monorepo/pull/149/files#diff-56acfe5c679c34adeeee54984d362e4a3b304afb5c23159c474de6da38553f05R183
Before:
After:

Change overflow from scroll to auto

---

packages/libs/eda/src/lib/core/hooks/computeDefaultAxisRange.ts
packages/libs/eda/src/lib/core/utils/default-axis-range.ts

This will resolve https://github.com/VEuPathDB/web-monorepo/issues/147. I have tested several cases, but one of the best and simplest way is to set the default value of the isNonZeroBaseline prop as true for. Actually, it is not used anywhere yet.
Here are various screenshots using year variable after applying this:

remove-zero-baseline-consideration

---

packages/libs/components/src/map/MapVEuMap.tsx

The button's position obscures the map scale (see bottom right of screenshot), plus could potentially obscure map markers. Low cost choice for now was to remove the button from the map UI.
Problem:

Remove gitter btn in map UI to prevent obscuring map info

---

packages/libs/eda/src/lib/workspace/EDAWorkspace.scss

Variable tree gets squished more aggressively in the map context. Switched the column width to use `minmax` to limit how small the width of the column gets.
Before:
After:

Use minmax for varTree column in subsetting UI

---

packages/libs/eda/src/lib/map/analysis/MapSideNavigation.tsx

Resolves https://github.com/VEuPathDB/web-monorepo/issues/167
Relates to changes made in https://github.com/VEuPathDB/web-monorepo/issues/125
Maps created by Google and Bing place the toggle in the center of the side menu and its size is proportionally small wrt its parent container. These changes reflect the "norm" established by those two powerhouses in the map world.
Screenshot of change:

Revert map side menu toggle btn size/placement changes

---

packages/libs/coreui/src/styleDefinitions/typography.ts
packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss
packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
packages/libs/eda/src/lib/map/analysis/MapVizManagement.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/MarkerConfigurationSelector.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/PieMarkerConfigurationMenu.tsx

Issue: #164 
Running `yarn nx start @veupathdb/eda`:
Running `yarn nx start @veupathdb/clinepi-site`:
**After**
Running `yarn nx start @veupathdb/clinepi-site`:

164: Tweak header styles to better match mockup

---

packages/libs/eda/src/lib/map/MapVEu.scss
packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/workspace/AllAnalyses.tsx
packages/libs/eda/src/lib/workspace/DownloadTab/index.tsx
packages/libs/eda/src/lib/workspace/WorkspaceRouter.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

closes #89
closes #140
closes #171
closes #173
This PR addresses several issues. Sorry about that. I can break it up into multiple PRs, if needed.
Of primary concern is the newly added **My Analyses** entry:

Map: saved analyses and downloads

---

packages/libs/eda/src/lib/core/components/variableTrees/VariableList.tsx
packages/libs/eda/src/lib/core/components/variableTrees/VariableTree.tsx
packages/libs/eda/src/lib/core/types/study.ts
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MapHeader.tsx
packages/libs/eda/src/lib/workspace/Subsetting/index.tsx

Addresses the 2nd and 3rd points of #169 
<br>
> (2nd point): the entity diagram is scrolled offscreen at the top.
**Solution**: The `FieldNode` component in the variable tree has some `scrollIntoView` logic. I disabled this logic in the map context.
<br><br>
> (3rd point): We use the word Filter to describe the filters, but Subset in heading. We need to either:
- use just one, always
- or add a bold title in the Filter display, indicating that when you filter, you are creating a subset
**Solution**: In the map header, the word 'Subset' has been replaced with 'Filtered' in hopes to better connect that value with the filter panel.

Adjust scroll behavior and verbiage in map's filtering UI

---

packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx

This PR makes the legend in the standalone map (SAM) "filter-aware".
Previously, there was some logic to use the variable's vocabulary directly, with no ordering, if its cardinality was smaller than the color palette. Otherwise, the top 7 values of the _entire study_ was used for the legend.
In this PR, that logic has been replaced with always using the top values of the _subset_. If the number of values is larger than the color palette, then an "other" value is included; otherwise, all of the values are used without the "other" value.
In the function `getMostFrequentValues`, I'm passing in `vocabulary`, but this is only used for the "low-cardinality" check. I'm not entirely sure we need that, anymore. @bobular can you comment on the utility of this check, especially given the changes in …

Make the SAM legend filter-aware

---

packages/libs/components/src/map/DonutMarker.tsx
packages/libs/eda/src/lib/core/components/filter/HistogramFilter.tsx

Resolves #209.
**Before**:
https://github.com/VEuPathDB/web-monorepo/assets/24446573/b71bcaaa-c972-4ac5-b019-54a32ee0128f
https://github.com/VEuPathDB/web-monorepo/assets/24446573/f84ebb3b-c470-4862-a24f-40cbab958ecc
☝ Here's the stack trace:
```
Reduce of empty array with no initial value
TypeError: Reduce of empty array with no initial value
```
Root cause: we're attempting to `reduce` an empty array without providing an initial value. If `props.data` is an empty array, calling `reduce` on it without an initial value raises this error. The array is empty only very rarely. Perhaps only when the user's thrashing around inputs like a punk. 👊 
Pictures say more than words. Here's the problem:

209: prevent interactions with filter from re-rendering the map or exploding the application

---

packages/libs/coreui/src/components/grids/DataGrid/HeaderCell.tsx
packages/libs/eda/src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

Use "height: auto" as default for table header and remove css targeting generated classname. Note that this issue is only happening on feature/qa/prod sites.
ETA: I also added a loading indicator in the site menu entry for the maps.
**Before**
**After**

Fix header issue in eda subset download table preview

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

I forgot that `useWdkService` has a signature similar to `useEffect`, and not including an array of dependencies causes it to run on every render. This was causing an infinite loop on genomics sites. This PR addresses that.

Fix ininite loop on genomics sites

---

packages/libs/eda/src/lib/core/components/computations/StartPage.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx

Note merge target is `sam-wire-floaters`
Partly addresses https://github.com/VEuPathDB/web-monorepo/issues/161
Removes a hardcoded app filter from MapAnalysis and only shows apps in `StartPage` (SAM+Mbio) that have client plugins defined.
Does not address what to do with the `projects` prop in the `apps` response.
At some point after we have removed the "single app mode" we will want to be able to configure different flavours of EDA (and potentially SAM) to use different apps.
So I'm not sure if/when we close #161, but @asizemore has confirmed it is OK to roll out this `StartPage` to MBio.

Remove hardcoded apps filtering in SAM and only display apps with plugins

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/options/types.ts
packages/libs/eda/src/lib/core/utils/visualization.ts
packages/libs/eda/src/lib/map/analysis/hooks/defaultOverlayConfig.ts
packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts
packages/libs/eda/src/lib/map/index.ts

Resolves https://github.com/VEuPathDB/web-monorepo/issues/218
Also moved the `__UNSELECTED__` token stuff to a more central location
Tested for categorical and continuous.
Continuous doesn't work yet for scatterplot - the back end response may be malformed. See https://github.com/VEuPathDB/EdaNewIssues/issues/642

SAM - fix floater overlay order

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx

Resolves #203 
Branched from `sam-wire-floaters` but I see that it also merges to `main` without problems.
Also removed an unused prop in the barplot config.

Sam - enable proportion markers

---

packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/web-common/src/routes.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

Resolves #212
New menu item:
Result of clicking the `My interactive maps` menu item (routes to `workspace/maps`):

Wire up a `workspace/maps` route

---

packages/libs/coreui/src/components/containers/DraggablePanel/index.tsx
packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MapLegend.tsx

#216 
Change list:
- Render the legend in a draggable panel.
- Ensure stacking order [as per a map UX meeting](https://epvb.slack.com/?redir=%2Farchives%2FCMQ8K9XRS%2Fp1684447704036989%255c%3Fthread_ts%255C%3D1684445660.278889%255C%26cid%255C%3DCMQ8K9XRS).
- Add logic to ensure the draggable panel remains on screen despite growing.  
<details> 
<summary id="warthog">See the logic in action!</summary> 
Before adding logic to constrain panel to browser screen:
https://user-images.githubusercontent.com/24446573/238075102-a0ff00ab-ff1c-4fb5-bb38-baec7903bda1.mp4 
After adding logic to constrain panel to browser screen:
https://github.com/VEuPathDB/web-monorepo/assets/24446573/d4610c85-18bf-42c1-b7fd-372ca4182431 
</details>
**Before**: 
**After**:

216: Convert static legend to draggable legend

---

packages/libs/coreui/src/assets/icons/index.tsx
packages/libs/coreui/src/components/theming/index.ts

Original compile issues with `yarn nx start @veupathdb/eda`
```
Compiled with problems:
ERROR in ../coreui/dist/assets/icons/index.js 70:0-69
export 'IconProps' (reexported as 'IconProps') was not found in './types' (module has no exports)
ERROR in ../coreui/dist/components/theming/index.js 3:0-34
export 'UITheme' (reexported as 'UITheme') was not found in './types' (module has no exports)
```
Looks like the compiler needs a hint about the reexport of a type.
Do we solve this here, or in the webpack/ts-config somehow? That's above my pay grade ;-) 
From my googling, I think `import type ...` and `export type ...` are typescript >= 3.8.x.
We are on 4.x so safe to proceed?

Fix build problem by making sure the typescript compiler knows import-export tokens are types

---

packages/libs/components/src/plots/MosaicPlot.tsx

Fixes https://github.com/VEuPathDB/web-monorepo/issues/182
Because the dummy x axis tick values were empty strings, the title had no labels to "automargin" against, so it was just positioned relative to the top of the plot. Changing the dummy labels to a single space gives it something to "automargin" against.
Removed tick angle because we don't actually have plotly-native tick labels.

Fix position of x axis title on mosaic plot

---

.github/workflows/npm-publish-sites.yml

This PR removes the ref_name from webpack cache key, since it refers to the git tag used for the release. Since those tags are unique, it makes the cache useless. Unfortunately, it is not possible to get a branch name for workflows triggered by release events.

Fix webpack cache key in github workflow

---

packages/libs/eda/src/lib/core/components/variableTrees/VariableList.tsx

closes #259 
This PR adds verbiage about multi-valued variables not being supported:

Append statement about multi-valued variables not being supported.

---

packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx

Replaces the `Chip` component with `active` string content with a checkmark per concerns about A) the `Chip` component looking like a button and B) an unclear parent-child hierarchy. The checkmark gives us better indentation that also better conveys the hierarchy.
Before:
After:

Use checkmark instead of chip to indicate active mapType

---

packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/cluster-graph/ClusterGraphCanvas.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/hooks/cytoscapeData.ts

Applies two commits from https://github.com/VEuPathDB/web-monorepo/pull/261 into a patch for the live ortho site.
Notes:
- this branch was made from `v1.0.16-patch.2` which was made from `v1.0.16-patch.1`
- picked only the two commits from the PR that were not merging main into the branch
Testing: 
- the cluster that was giving us headaches looks good!

Patch ortho clustergraph layout

---

packages/libs/multi-blast/src/lib/controllers/BlastQuestionController.tsx
packages/libs/preferred-organisms/src/lib/components/OrganismParam.tsx
packages/libs/wdk-client/src/Actions/QuestionActions.ts
packages/libs/wdk-client/src/Controllers/QuestionController.tsx
packages/libs/wdk-client/src/StoreModules/QuestionStoreModule.ts
packages/libs/wdk-client/src/Utils/ParamValueStore.ts
packages/sites/genomics-site/webapp/wdkCustomization/js/client/component-wrappers/QuestionController.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx

This PR adds functionality that saves and reuses the value of organism parameters across searches.
This can be tested on https://dfalke-b.vectorbase.org

Save organism param value and state across searches

---

packages/libs/eda/src/lib/core/hooks/workspace.ts

Fixes #324 
Turned out to be relatively simple.
In our "augmented study metadata" somehow some dates are appended `T00:00:00Z` and others `T00:00:00.000Z`. I'm not sure why. But I thought it was wise to handle both. I made the `Z` optional while I was at it.

Fix problem with filtered date variables breaking visualization axis variables

---

packages/libs/wdk-client/src/Controllers/QuestionController.tsx

This PR fixes an issue where search forms are not loading on internal dataset pages (e.g., RNA Seq)

Ensure the correct searchName and recordClassName are used

---

packages/libs/wdk-client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts

closes https://redmine.apidb.org/issues/51399
This PR fixes a bug where the filter param clobbers the parameter's value on revise.

Fix filter param initialization in revise form

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts

This will activate timeline plot by setting timeline plugin. In this initial PR, it is activated for SAM's X-Y Relationship as shown in the screenshot below.

activate timeline plot

---

packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss

With https://github.com/VEuPathDB/EdaDataService/pull/292, resolves data service [issue 288](https://github.com/VEuPathDB/EdaDataService/issues/288).
Goal of 288: Change beta div scatter name to Dimensional reduction scatter plot. The data service PR changes the name, but then the viz picker title is super long. This PR adds a max width so that the name wraps. 
An alternative route was to use the same strategy as the mosaic and 2x2 plots, where we break on ', '. But it doesn't really make sense to have a comma in the Dimensional reduction scatter plot name when it's all written out (like on the visualization page itself).

add maximum width to viz picker title

---

packages/libs/eda/src/index.tsx
packages/libs/study-data-access/src/data-restriction/DataRestrictionUtils.js
packages/sites/clinepi-site/webapp/js/client/main.js
packages/sites/genomics-site/webapp/wdkCustomization/js/client/bootstrap.js

This PR remove redux middleware used for data restrictions. Need to make sure we won't need this in the future, before merging.
This was requested by JB (on slack) when qa.vectorbase , eda-enabled, had eda-rbld missing some tables needed for the permissions endpoint  and searches were breaking.

Remove redux middleware that is no longer needed

---

packages/libs/wdk-client/src/Components/Mesa/Ui/DataCell.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx

Fixes r51417
This PR includes
- Add "Read more/less" button to overflowing Organism cells
- Removes `display: flex` from the searches table column cells
- Uses Mesa cell renderers as React Components
**Collapsed**
**Expanded**

Add a "Read more" link to tall cells in InternalDataset pages

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/PathwayRecordClasses.PathwayRecordClass.jsx

Resolves issue with rendering labels in Cytoscape. The desired behavior is to not render labels until zoomed in at a certain level. Currently, the client passes `null` as the label when zoomed out of the zoom threshold which results in `null` being rendered on the Cytoscape graph.
**Screenshot of the problem as it first renders:**
We can instead pass in an empty string when we don't wish to render a label.
**Screenshot of the resolution as it first renders:**

Change null labels to empty strings

---

packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx

Leveraging the usePromise to deliver the new vocabulary only when the data request has completed.
The main thing to know is that whenever the callback function inside the usePromise returns undefined, the payload in, for example `rawMarkersPayload.value` remains as the previous successful return value.
The implementation is ugly - the naming is nasty in particular (I didn't like `rawMarkersDataAndVocabulary` either!). It's hopefully possible to do something like this with fewer ugly changes (e.g. lots of `rawMarkersPayload.value?.rawMarkersData`)
A bonus advantage of this approach is that the markers and legend don't change until the data has come back from the back end.

Suggestion to synchronise vocabulary and rawMarkersData dependencies

---

packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx

Fixes a bug with the `ValuePicker`s for Group A and Group B values.
<h3>The bug</h3>
Changing the comparator var resets the group A and group B values and the component will re-render a handful of times. As a result, the `selectedValues` will be assigned a new empty array literal during <strong><em>each render</em></strong> due to this line: <br /><br />
<code>selectedValues={configuration?.comparator?.groupA ?? []}</code>
<br /><br />
The `ValuePicker` component sees this as a new state due to object equality/reference reasons and thus it will re-render and reset its state back to an empty array.
<h3>Steps to reproduce the bug</h3>
<ol>
<li>Select a comparator var</li>
<li>Quickly-ish open a group selection list and make a selection</li>
<li>Notice  selection state disappears</li>
</ol> …

Fix lost selection state in value picker

---

packages/libs/web-common/src/controllers/ExternalContentController.tsx

closes #379
This PR includes searching for elements with a `name` attribute that matches `location.hash`.

Update querySelector to find elements with matching name attribute

---

packages/libs/components/src/components/widgets/NumberAndDateInputs.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Relates to second-to-last item in https://github.com/VEuPathDB/web-monorepo/issues/358
Note: I passed `step={0.001}` to the `P-Value` input but the `Fold Change` step remains undefined, thus remains the same default behavior (step of 1).

Add step prop to NumberInput component and use in VolcanoPlot

---

packages/libs/eda/src/lib/core/components/computations/plugins/Plugins.scss
packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ValuePicker.tsx

Resolves 2nd and last items from https://github.com/VEuPathDB/web-monorepo/issues/358
In the process of making these adjustments, I took the opportunity to pay off some tech debt by creating a new SASS file that replaces the inline styling used in our plugin configuration menus and in each plugin's description component.
1. New viz with no selections. Group A, swap button, and Group B disabled. Notice I'm using the native `title` tooltip but would we prefer a tooltip component?
2. Group comparison variable now chosen so Group A and Group B are enabled. Notice the swap button remains disabled. Also note that we are unable to render a tooltip explaining why it's disabled due to the way MUI handles disabling their components, but I suspect users will figure it out easily enough.
3. Swap …

Adjust diff abundance configuration layout

---

packages/libs/components/src/plots/VolcanoPlot.tsx

Resolves #372 
NOTE: I went ahead and also prevented `significanceThreshold` lines from venturing beyond the graph in spite of how unlikely users would stray beyond them (see video!).
Screencast below demonstrates the new behavior in this order:
1. Negative fold change line
2. Positive fold change line
3. Sig line below the graph
4. Sig line above the graph
https://github.com/VEuPathDB/web-monorepo/assets/69446567/31ed48c7-ec27-4725-987b-0f01309cb279

Prevent threshold lines from rendering outside graph

---

packages/libs/wdk-client/src/Controllers/ResultTableSummaryViewController.tsx
packages/libs/wdk-client/src/Views/ResultTableSummaryView/ResultTable.tsx
packages/libs/wdk-client/src/Views/ResultTableSummaryView/ResultTableSummaryView.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/DownloadsFilter.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/DownloadsTable.tsx

This PR updates the UI of the downloads page to better handle the organism parameter:
- Move the organism param to the top
- Integrate preferred organisms
- Add headings above params
- Add counts to table
Note, this requires some model changes before it can be merged, which I will take care of when this is approved.

Genomics download UI updates

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/selectorIcons/TimeSeriesSVG.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts

Resolves #323 
Adds time series viz icon. Used in the map.
We've had lots of discussion around this icon in slack so i picked a version folks were okay with and went for it :) 
I'm hoping that once it's really on the site we can better decide how we may want to modify it or that it just needs to be distinct from other icons.

add time series viz icon

---

packages/libs/wdk-client/src/Components/DataTable/DataTable.css
packages/libs/wdk-client/src/Components/DataTable/DataTable.tsx

Resolves [redmine#51970](https://redmine.apidb.org/issues/51970).
**NOTE**: I opted against using [Mesa's `RowCounter` component](https://github.com/VEuPathDB/web-monorepo/blob/main/packages/libs/wdk-client/src/Components/Mesa/Ui/RowCounter.jsx). I felt the props in `RowCounter` would have required more paging state to be held in `DataTables` than we really need.
Screenshots of this work:

Add row counts to record page tables

---

packages/libs/components/src/plots/VolcanoPlot.tsx
packages/libs/components/src/types/plots/volcanoplot.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Resolves #433 
This PR adds a `displayLabel` to the `VolcanoDataPoint` so that if defined, the tooltip can show the user-friendly name instead of the pointID we get from the backend. The pointID is formatted {entityID}.{variableID}, so we can use this to find a display label.
Not too much else to say about this one i think!

use variable display name in tooltip

---

packages/libs/wdk-client/src/Utils/UserPreferencesUtils.ts

Dynamic attributes are currently ignored. This PR fixes that.
Test with https://qa.plasmodb.org/plasmo.b65/app/workspace/strategies/import/8a60c52662fdffc0
**Before**
**After**

Check dynamic attribute for known columns

---

Dockerfile

The docker build fails in some environments due to excessive memory usage. This PR sets a node option to address that.

Reduce overall memory used by docker build

---

packages/libs/components/src/components/plotControls/PlotBubbleLegend.tsx

This issue was that the maxSizeValue from the back end was 196,503. The `toPrecision(1)` rounded this up.  If it had been 149,999, it would have been rounded down and the max bubble size would have been 200,000 as desired.  I've changed the algorithm a bit to hopefully do the right thing.
Before:
After:

Change rounding algorithm in bubble size legend

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

closes #455
This PR adds some logic to prevent reordering series data when the xaxis variables is a low-cardinality continuous variable. I'm not sure if we want to apply this to other visualization types. For now, only lineplot allows continuous variables on the xaxis.

Do not attempt to reorder series data for continuous x-axis variables

---

packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/appState.ts

Resolves https://github.com/VEuPathDB/web-monorepo/issues/403
I'm marking this as ready to merge while we're still considering the idea of general UI persistence. Further work can be in another ticket.

Side panel UX improvements

---

packages/libs/wdk-client/src/StoreModules/QuestionStoreModule.ts
packages/libs/wdk-client/src/Views/Question/Params/EnumParam.tsx
packages/libs/wdk-client/src/Views/Question/Params/EnumParamUtils.ts
packages/libs/wdk-client/src/Views/Question/Params/SelectionInfo.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/DownloadsFilter.tsx

Changes include:
- Only persist param values when a search is run successfully (for all searches)
- On download page, if user clears all in org param, then show an error message
This can be tested at https://dfalke-b.vectorbase.org/vectorbase.dfalke/app/downloads

Genomics downloads handle invalid param selection

---

packages/libs/web-common/src/styles/AllSites.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/styles/home-page-layout.scss

Make sure page footer is not on top of main content elements

---

packages/libs/components/src/components/widgets/LabelledGroup.tsx
packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Resolves #443 and #357
Regarding issue 357 (viz picker alignment), I opted to set the width of the container to `13em`, which enforces a similar wrapping of our longest description string on the live site while fixing the icon misalignment. Personally, it doesn't bother me that the text extends beyond the icon, which is why I opted not to set the container's width to `10em`, equal to the button's width.
And here's a screenshot that reflects the changes for issue 447:

Tweak mbio layouts

---

nx.json
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

This is a quick workaround to deal with an error that is thrown for non-eda enabled genomic sites.

Hardcode map link

---

packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx

Add import route and construct sharing url

---

packages/libs/components/src/stories/plots/VolcanoPlot.stories.tsx
packages/libs/components/src/types/plots/addOns.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Resolves #67 
After a long discussion in the data viz meeting yesterday (see notes [here](https://veupathdb.atlassian.net/wiki/spaces/FG/pages/360513589/Wednesday+2023-08-30+1PM)), finally we came to an agreement.
I did double check contrast ratios for tooltips as well! Nothing had to change there :)

updated volcano colors for accessibility and function

---

packages/libs/eda/src/lib/map/analysis/appState.ts

This PR fixes an issue where non-root-entity featured variables are not used as the default map variable.

Remove entity from function call, so that featured variables are checked for the entire entity tree

---

packages/libs/eda/src/lib/core/components/computations/plugins/index.ts

For b65, we need to release the site with differential abundance turned off. There is a change we can turn it back on with a patch later, but initially at least it should be turned off.

turn off diff abund

---

packages/libs/web-common/src/components/SiteSearch/SiteSearch.scss
packages/libs/web-common/src/components/SiteSearch/SiteSearchHooks.ts
packages/libs/web-common/src/components/SiteSearch/SiteSearchInput.tsx
packages/libs/web-common/src/components/SiteSearch/TypeAheadInput.tsx

This PR adds a search history menu to the site search input. It will be visible if the user has clicked the input, and either the input is empty or its value matches the query param in the url. The menu will disappear if the user selects an option, changes the input value, or clicks outside of the input widget.

Add search history menu to site search input

---

packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
packages/libs/eda/src/lib/core/types/study.ts

Resolves #471 and must have for b65
This PR adds a temporary frontend filtering mechanism for the collection variables. In our new database we have both Relative Abundance data and Absolute Abundance data (along wiht lots of other data types). Each app can only handle _either_ the relative abundance or absolute abundance data. The collection vars now include some added properties that we can use to do this filtering on the frontend. 
However, the frontend is _not_ where this filtering should go long term! The infra team is hoping to work on a mechanism for the backend to declare which collections are appropriate for which app, in a way that's similar to how the vizs say they can take categorical but not continuous vars on the x axis, for example. So, #472 was created to ensure we delete …

Fix 471 appconstraints

---

packages/libs/eda/src/lib/core/components/visualizations/options/types.ts
packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts

Fixes #492 
I update the overlay help verbiage for bubbles:
ETA, I also updated the default position of the floater so it doesn't overlap with the timeslider.

Disable floater overlays in bubble mode

---

packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerConfigurationTable.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerPreview.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/PieMarkerConfigurationMenu.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/426. Detailed descriptions are listed in the following:
- requirements (taken from the ticket)
: addressed
: I think that one of the best approach is to use acronym for certain radio button label: there are not much room for reducing the spacing in the radio buttons, I suppose. I chose deviation as dev. as it is commonly used as a short word: or we may use Std as the acronym of the standard deviation. Just in case, full word is explained at button title, but perhaps a text below the radio buttons can be utilized as well.
: addressed
: for both cases, there were no implementation on the ellipsis for both variable picker and data table. After seeking out a solution, perhaps the easiest solution is to set max width, then …

slim down donut and bar plots panels

---

packages/libs/eda/src/lib/map/analysis/MapVizManagement.tsx

Resolves #427 
Previously, deleting a floater always invoked `setActiveVisualizationId(undefined)`. Now, we'll only do so if the viz being deleted is the active viz.
**NOTE**
The deletion will update `analysisState`, causing the loader to spin on the active viz. This may be another thing to consider when we have our deep think about our data requests. As a user, I'd be a bit confused why deleting a non-active viz results in a loading state. This issue feels a bit out of scope for this ticket, but perhaps it's not? Thoughts on if I should investigate further in the context of this ticket, or should it wait until our proper deep think?

Add condition to deleting marker floaters logic

---

packages/libs/http-utils/src/FetchClient.ts

This PR includes the traceid header value in FetchClient error messages. This is useful for finding associates service logs.

Add traceid to FetchClientError message

---

packages/libs/components/src/map/ChartMarker.tsx
packages/libs/components/src/map/DonutMarker.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerPreview.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx

Resolves #326 
This PR addresses two bugs in marker previews:
- the map markers receive a `dependentAxisRange` that the marker previews were not receiving
- providing the same `dependentAxisRange` to the marker preview appears to resolve this issue
- in proportion mode, the data was erroneously adding together (in a reduce function) _**proportion**_ values that corresponded to the same overlay label in the same manner that we do for counts values; this resulted in an erroneous number displayed as `totalCount` in the marker preview
- now, we add a `count` property to the data that is used to determine `totalCount` irrespective of the plot mode

Resolve marker preview bugs w/ bar plot map type 

---

packages/libs/components/src/plots/BipartiteNetwork.tsx
packages/libs/components/src/plots/Network.tsx
packages/libs/components/src/stories/plots/BipartiteNetwork.stories.tsx
packages/libs/components/src/stories/plots/NodeWithLabel.stories.tsx
packages/libs/components/src/types/plots/addOns.ts
packages/libs/components/src/types/plots/network.ts

Resolves the first task of #512 
To Dos:
Current progress:
Additional notes:
- the visualization or frontend correlation app plugin will need to set the link colors because that's not a bipartite network-specific decision.
- the bipartite network component handles the positioning of the nodes so that when we add a click-to-reposition feature in the future, the frontend can do the whole thing.
Left for later:
- handling long node names. Should be just a max with and we see "blah..." and on hover see the whole name"
- Overriding defaults for plot layout. I expect we'll need to do this a bit down the line but we can wait and see what we'll really need

Add bipartite network component

---

packages/libs/web-common/src/components/reporters/BedAndSequenceGenomicSequenceReporterForms.jsx
packages/libs/web-common/src/components/reporters/BedGeneReporterForm.jsx
packages/libs/web-common/src/components/reporters/ReporterForms.scss
packages/libs/web-common/src/components/reporters/SequenceFormElements.jsx
packages/libs/web-common/src/components/reporters/SequenceFormFactory.jsx
packages/libs/web-common/src/components/reporters/SequenceGeneReporterForm.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/TranscriptRecordClasses.TranscriptRecordClass.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/util/transcriptFilters.js

Addresses the following points [from this issue](https://github.com/VEuPathDB/EbrcWebsiteCommon/issues/193):
> 1. Mockup updated after UX meeting Jan 18 2023 https://docs.google.com/presentation/d/1m43IHO6BnkXHpusYR2cnJgWdgazm8jCy1euqBiNyKRA/edit#slide=id.p
> 2. Add a checkbox as in the tabular reporter to select one transcript per gene to all report forms where this is now supported. See
https://github.com/VEuPathDB/ApiCommonWebsite/issues/117
Below is a screenshot of the UI changes [modeled off of this mockup](https://docs.google.com/presentation/d/1m43IHO6BnkXHpusYR2cnJgWdgazm8jCy1euqBiNyKRA/edit#slide=id.p).
Note that there's a comment in the code that wonders if the flattening of the defline options, which requires adding `gene_id` to the `deflineFields` array, would cause trouble …

Tweak UI for new SRT

---

packages/libs/components/src/plots/BipartiteNetwork.tsx
packages/libs/components/src/stories/plots/BipartiteNetwork.stories.tsx
packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/index.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx

Resolves tasks in #512 
This PR:
Using the `add-correlation` of the data service and the rest of the services on their QA images, we can get the following: 
https://github.com/VEuPathDB/web-monorepo/assets/11710234/9a31e7b7-de01-49f1-ac27-122864e6dd9e
Turns out that though it's not so hard to generate fake data, it is a little more involved to sub in the requests and compute job status and such so that we can make the app appear and think that the Step 3 should be enabled. So I did a bit on the backend to help us at least just see the app (see `add-correlation` branch in the data service) but stopped there since we can still see the network enough to verify that it works!
If you do test with the local backend, do not try actually selecting the data in Step 1. The app will try to make a …

added correlation plugin

---

packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Resolves #541 
Discussed in the mbio meeting, @dpbisme raised concerns about the method selection becoming too complicated for users. Instead he suggested choosing the method based on the data, so that the user doesn't have to choose. 
UPDATE: New decision is to only use the 'Maaslin' method for this first roll out. Code has been updated so as to only use Maaslin as the differential abundance method.
This PR 
1. Removes the Method input selector
2. Sets the `differentialAbundanceMethod` to always be `Maaslin`
3. Reports the method used in the volcano plot subtitle.

Use Maaslin only and report method in plot

---

packages/libs/coreui/src/components/containers/DraggablePanel/index.tsx
packages/libs/eda/src/lib/core/components/layouts/FloatingLayout.tsx
packages/libs/eda/src/lib/core/components/layouts/types.ts
packages/libs/eda/src/lib/core/components/visualizations/VisualizationTypes.ts
packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/MapVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx
packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MapVizManagement.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts

Closes https://github.com/VEuPathDB/web-monorepo/issues/99

Collapse button for floating viz controls

---

packages/libs/eda/src/lib/core/utils/trim.ts
packages/libs/eda/src/lib/map/analysis/EZTimeFilter.tsx

Fixes #514 
As suggested in https://veupathdb.atlassian.net/wiki/spaces/WG/pages/367951873/2023-09-14+Map+UX by @dmfalke and others. The timeslider will now honour the "big filters" but not the viewport or any "little filters".
In theory we don't need the filter-sensitive part, but it will reduce the number of bins coming back from the `distribution` service call and thus help marginally with performance.

Added filter- and subset-sensitivity to timeslider

---

packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.ts

I wasn't too keen on the map automatically zooming to data whenever the user zoomed out to zoom level 1.  This brings back the old behaviour without too much bother.

Bring back old FlyTo behaviour for now

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts

Resolves #578 
The backend sometimes sends an adjustedPValueFloor = null. This PR adds that option to the api.

allow adjustedPValueFloor to also be null

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/529.
Truncation warnings are added for both independent and dependent axes. A screenshot is attached in the following:

add truncation warning to Volcano Viz

---

packages/libs/wdk-client/src/Core/Style/wdk-Common.scss
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx

This PR includes the following changes:
1. Puts visible help in an info box
2. Add global style rules for `<dl>` blocks: `<dt>` and `<dd>` are on the same line, and `<dt>` is in bold.

Update visible help styling

---

packages/libs/wdk-client/src/Actions/RecordActions.ts
packages/libs/wdk-client/src/Controllers/RecordController.tsx
packages/libs/wdk-client/src/Core/routes.tsx
packages/libs/wdk-client/src/Views/Records/RecordMain/RecordMainSection.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx

This PR introduces a simplified version of a record page, that can be embedded in popups. Attributes and tables can be specified via query params.
Route paths for this page look like:
```
/embed-record/long_read_transcript/TALONT000034884_DS_2e2a681fa9?tables=SampleInfo
```
which results in a page that looks like:

Simple record page

---

packages/libs/preferred-organisms/src/lib/components/OrganismParam.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/OrganismFilter.tsx

Resolves https://redmine.apidb.org/issues/50190
Added a filter for reference strains to below components. To be frank, I don't love the vertical bar that separates the toggles in the `OrganismFilter`, but I've left it for now.
`OrganismParam`:
`OrganismFilter`:

Add more reference org filters

---

packages/libs/eda/src/lib/core/hooks/study.ts
packages/libs/http-utils/src/FetchClient.ts
packages/libs/wdk-client/src/Views/UnhandledErrors/UnhandledErrors.scss

This PR will throw errors caught when attempting to load eda study metadata, if it is not a `FetchClientError`. This change will cause io-ts error to get thrown, which is useful to prevent masking that error. The styling of the error modal is also updated.

Eda study type error

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss

I chose to make it 100% font size instead of the previously-set 80%.

Increase row count font size in beta Downloads table

---

packages/libs/preferred-organisms/src/lib/components/OrganismParam.tsx

Moved to the right of the search box, similar to the site search and org prefs implementations.

Reposition reference filter

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss

Resolves #552 
Leverages a `min-width` property to prevent table's horizontal scroll behavior.

Add min-width to prevent confusing overflow UX

---

packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx

This PR fixes an issue where a supporting plot will appear for all map types, regardless of where it was created.

Use correct mapType for supporting plots

---

.gitignore
packages/libs/eda/src/lib/core/hooks/study.ts
packages/libs/eda/src/lib/core/types/study.ts
packages/libs/user-datasets/src/lib/Components/Detail/IsaDatasetDetail.jsx
packages/libs/web-common/src/controllers/UserDatasetRouter.ts
packages/libs/web-common/src/routes.jsx
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx

closes #550 
This PR add a link to the standalone map for user datasets that have map data. It is using the relatively new `hasMap` property of the eda study record.
@jernestmyers I assigned you, so you are aware of these changes. Do you see any conflicts with your VDI work?

User datasets:  Add  link to standalone map for ISA user datasets

---

packages/libs/eda/src/lib/core/hooks/analysis.ts
packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/appState.ts
packages/libs/eda/src/lib/workspace/ComputationRoute.tsx

This PR updates the logic related to `singleAppMode` in the EDA workspace. Previously, we assumed the first `computation` in the `analysis.descriptor.computations` array would match the `singleAppMode` computation type. The precludes the possibility that the analysis was created in some other context, or that the analysis contains other computations.
Now, we will look for any analysis that matches the `singleAppMode` type. If one is not found, one will be created before rendering the viz tab. Additionally, `singleAppMode` is being passed to `MapAnalysis`, to ensure that the computation is always created when the website is configured to use `singleAppMode`.
This is to enable using both the EDA Workspace view, and the Standalone Map view, for a single analysis object.
ETA this also …

Eda:  better handle single app mode

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/routes.jsx

Resolves https://redmine.apidb.org/issues/52962
In `VEuPathDB`, we now will render the page below which links to each site's downloads UI.

Render links to site downloads page in VEuPathDB site

---

packages/libs/eda/src/lib/core/components/AnalysisError.tsx
packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/workspace/AnalysisPanel.tsx
packages/libs/http-utils/src/FetchClient.ts
packages/libs/wdk-client/src/Components/Layout/Page.tsx

Fixes #518 
This PR adds some specific rendering when an error is encountered, while trying to load an analysis.
Additionally, the use of Banner was replaced with a more conservative UI, for studies without geo data.

Display useful message to user when analysis fails to load

---

packages/libs/web-common/src/App/NewsSidebar/News.jsx
packages/libs/web-common/src/App/Showcase/Showcase.jsx

While working on https://github.com/VEuPathDB/web-monorepo/issues/642 I noticed that I introduced a key error with my `CollapsibleDetailsSection` work. I am addressing that particular key error and the rest of that ticket on a separate branch, but I went ahead and resolved the other two annoying key errors re: `News` and `CardList`.

Fix annoying react key errors in EDA site homepage

---

packages/libs/web-common/src/components/reporters/SequenceFormFactory.jsx

Resolves https://github.com/VEuPathDB/web-monorepo/pull/523#issuecomment-1812597494
**NOTE**: Pulling the data to check if it's a `transcript` feels brittle. Is there a more robust way?

Render transcript filter in SRT for genes only

---

packages/libs/eda/src/lib/map/MapVeuContainer.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx

Fixes #637 
This PR prevents useQuery from retrying queries when they fail. It also prevents useQuery from refetching queries when the browser window is refocused. Finally, the `isLoading` props for legend uses the `isFetching` property of a useQuery result.

Deal with react-query errors and retry settings

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx

Resolves #663 
Updated the default effect size threshold to 1 (effectively +/- 1). Also renamed the var to make the concept more general. "Effect size" is the general term for that measure, whereas "model coefficient" (from maaslin) and "log2FoldChange" (from deseq) are specific to the methods.
Here's a pic
Note - any testing needs to be done with a cached completed compute bc they're failing right now. The above was with diabimmune

update default effect size and var names

---

packages/libs/eda/src/lib/core/components/computations/plugins/index.ts

Resolves #619 
Turns off the correlation app so that it will not get released with b66.
Can be reverted after the release!
From PR (Correlation should show up between diff abund and Distributions, but it's not there!)

temporarily turn off correlation

---

packages/libs/wdk-client/src/Components.ts
packages/libs/wdk-client/src/Core/Style/Icons/BetaIcon.tsx
packages/libs/wdk-client/src/Core/Style/Icons/NewIcon.tsx
packages/libs/wdk-client/src/Utils/WdkModel.ts
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx
packages/libs/web-common/src/components/homepage/SearchPane.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/wrapWdkService.tsx

This PR adds support for an `isBeta` property on wdk questions. This can be used to display a beta icon when rendering the display name of the question.
This PR also hard codes `isBeta` for long read searches.
_Note, I will be merging this PR without a review so it can be included in the next release._

Genomics add beta icon to searches

---

packages/libs/components/src/map/BoundsDriftMarker.tsx

This will possibly address the single click issue while double clicking a marker. Branched out from https://github.com/VEuPathDB/web-monorepo/pull/588.

a solution to prevent single click while double clicking

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/hooks/workspace.ts
packages/libs/eda/src/lib/core/types/study.ts
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BubbleMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/utils/defaultOverlayConfig.ts

Fixes #670 
- do we want to modify ValuePicker/SelectList so that disabled items have greyed out labels but active deselectable checkboxes (but not reselectable?)

Improve UX for bubble marker proportion configuration when filters are active on the variable

---

packages/libs/coreui/src/components/containers/DraggablePanel/index.tsx
packages/libs/eda/src/lib/map/analysis/DraggableLegendPanel.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/624
Similar to EDA legend, the panel title at Draggable panel now has ellipsis (25 characters like EDA) and mouseover tooltip (screenshot). Also, minWidth is set to the Draggable panel so that it cannot be too narrow for bubble marker: set to be 120px based on Country variable and considering the width of scale bar.

ellipsis of legend title and tooltip for SAM and minWidth

---

packages/libs/wdk-client/src/Controllers/RecordController.tsx
packages/libs/wdk-client/src/Core/routes.tsx
packages/libs/wdk-client/src/Views/Records/Record.css
packages/libs/wdk-client/src/Views/Records/RecordUI.jsx
packages/libs/web-common/src/component-wrappers/RecordPage.jsx
packages/libs/web-common/src/styles/client.scss

closes #730 
This PR introduces a new optional boolean `compressUI` prop that can be passed to `RecordController`. When `true`, a `wdk-Compressed` class is added to the `wdk-RecordContainer` element, allowing various style overrides to compress the page's layout.
Overrides include:
- Smaller font size.
- Less white space in table and between page elements.
- Scrolling tables w/ fixed header. Alternatively, we can make the record overview fixed, but I think this option works well when there is only one table on the page.  
- Removed sidebar.
**Before:**
**After:**

Update styling for embedded record pages

---

packages/libs/eda/src/lib/core/components/computations/ComputationInstance.tsx
packages/libs/eda/src/lib/core/components/computations/Types.ts
packages/libs/eda/src/lib/core/components/computations/ZeroConfiguration.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/countsAndProportions.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/distributions.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/pass.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/xyRelationships.tsx
packages/libs/eda/src/lib/core/components/visualizations/VisualizationTypes.ts
packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts

fixed #735 
This PR adds some defensive code to handle `undefined` compute configs. It also introduces more specific types for compute configs (`null | Record<string, unknown>`).
- If a compute config is undefined, stub in the default using the plugin's createDefaultConfiguration function
- Require compute plugins to return either `null` or `Record<string, unknown>`, which better models our expectations.

Better handling for `undefined` compute configs

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx

Resolves #738 
Moves the definition of `strokeWidthMap` inside the `cleanedData` `useMemo`. We need to keep the calculation of min and maxDataStrokeWidth outside that `useMemo` because the legend also uses those values.
Tested locally and i'm not seeing that darn continuous rerendering anymore!

move stroke map logic to prevent continuous rerenders

---

packages/libs/eda/src/lib/core/components/computations/StartPage.tsx
packages/libs/eda/src/lib/core/components/computations/Types.ts
packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss
packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx
packages/libs/eda/src/lib/core/utils/study-metadata.ts

Resolves #731 , child of #667
The two correlation apps require particular data to run. Some studies don't have these data, so for those cases we want to show a disabled app. More specifically,
- correlation assay x metadata requires at least one continuous metadata variable on an entity that is on a one-to-one path with the assay
- correlation assay x assay is specifically for taxa vs functional data. "Functional data" means data from a metagenomic assay, which is an entity that not all studies have. 
I also used the same architecture for the above checks to address #723 
To Dos
For testing, some helpful studies include:
- BONUS. Both corrleation apps should be available
- DailyBaby. Should have only the assay x metadata correlation app
- HMP WGS. Should have only the assay x assay …

Disable apps based on study metadata

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts

wip
i made this change so i could test some backend changes locally, but would like to know if people have reasons why i shouldnt merge it. mostly im collecting thoughts/ opinions right now, if anyone has any.
i made a change in https://github.com/VEuPathDB/EdaDataService/pull/342 that means sometimes well see empty plot refs. theyre just variables that i am keeping track of for one reason or another but arent actually in the plot. in this case it was so they could be used to properly impute zeroes in the popbio megastudy.
there is also a pr to discuss what these should actually look like as json https://github.com/VEuPathDB/veupathUtils/pull/33

allow plot references to be null or omitted

---

packages/libs/eda/src/lib/core/hooks/analysis.ts
packages/libs/eda/src/lib/map/MapVeuAnalysisList.tsx

fixes #675
This PR uses an EventEmitter to keeps changes to analyses synchronized between the `useAnalysis` and `useAnalysisList` hooks.

Map sync header list

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx

resolves https://github.com/VEuPathDB/web-monorepo/issues/764
this will keep from breaking things that are currently working. idk if there were other changes you were anticipating..

Bipartite network api update

---

packages/libs/components/src/plots/Barplot.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/760.
Screenshots are attached for before and after this PR. SCORE S. mansoni Cluster Randomized Trial is used.

limits decimal points for SAM barplot marker

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx

so im not worried about this being 'good' or 'pretty'. i dont think this is a thing to release, just a thing to let people play w prefilters. then we can decide what we do and dont like for defaults, whether to offer user controls, if there are other things wed like to prefilter on, etc. then at that point presumably this gets reverted or obviated by some newer change.

draft some correlation prefilter inputs

---

packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
packages/libs/eda/src/lib/workspace/ComputationRoute.tsx

Closes #778 
This PR removed the computation ID from the url of a visualization. This makes the url stable when changing the configuration of a compute.

Remove compute id from route

---

packages/libs/eda/src/lib/core/components/computations/Utils.ts
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
packages/libs/eda/src/lib/core/components/variableSelectors/VariableCollectionSingleSelect.tsx

Resolves #749 
Restricts the collection inputs for the Functional Associations correlation app. The first collection input should be restricted only to taxa, and the second only to functional data. In our case, functional data means pathway or gene abundance data.
With these tough restrictions, often all collections on an entity might get filtered out, which would leave a lonely entity name in the `VariableCollectionSelectList`. I've updated that component to remove entities with no items (collections).
Testing - use my dev site as a backend. QA backend is being updated today.

Restrict inputs for functional associations app

---

packages/libs/coreui/src/components/Mesa/Ui/DataTable.jsx
packages/libs/coreui/src/components/Mesa/style/Ui/HeadingCell.scss

Fixes https://github.com/VEuPathDB/web-monorepo/issues/777

Restore interactvitiy of Data Table sticky column headers

---

packages/libs/coreui/src/components/Mesa/types.ts
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerConfigurationTable.tsx
packages/libs/eda/src/lib/workspace/PublicAnalyses.tsx
packages/libs/multi-blast/src/lib/hooks/allJobs.tsx
packages/libs/multi-blast/src/lib/hooks/combinedResults.tsx
packages/libs/study-data-access/src/study-access/components/UserTable.tsx
packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
packages/libs/wdk-client/src/Components/Shared/CommonResultTable.tsx
packages/libs/wdk-client/src/Views/AttributeAnalysis/AttributeAnalysisTabs.tsx
packages/libs/wdk-client/src/Views/Strategy/PublicStrategies.tsx
packages/libs/wdk-client/src/Views/Strategy/StrategyInputSelector.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/genomeSummaryView/FeatureTable.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/genomeSummaryView/ResultsTable.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/stepAnalysis/StepAnalysisGoEnrichmentResults.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/stepAnalysis/StepAnalysisHpiGeneListResults.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/stepAnalysis/StepAnalysisPathwayEnrichmentResults.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/stepAnalysis/StepAnalysisWordEnrichmentResults.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/utils/dataTables.ts

This PR removes `unknown` types from `Mesa` type definitions.
A big change is that `MesaColumn` now takes two generic types: `Row` and `Key`. The `Row` type is required, and the default for `Key` is `keyof Row`. This covers most use cases, and allows us to better infer the type of `value` in `CellProps`.
Getting these types right is tricky, because `Mesa` tries to allow any data structure to be used for a row, and to allow the consumer to compute the rendered value however it sees fit.
In most cases, we simply use objects as rows, and the keys of those objects as column keys, which this PR attempts to make easy.

Remove `unknown` types

---

packages/libs/web-common/package.json
packages/libs/web-common/src/hooks/diyStudySummaries.tsx
packages/sites/clinepi-site/package.json
packages/sites/clinepi-site/webapp/js/client/controllers/UserDatasetRouter.tsx
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
packages/sites/clinepi-site/webapp/js/client/wrapStoreModules.js
packages/sites/clinepi-site/webapp/js/client/wrapWdkService.ts
packages/sites/mbio-site/package.json
packages/sites/mbio-site/webapp/wdkCustomization/js/client/controllers/UserDatasetRouter.ts
packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx
packages/sites/mbio-site/webapp/wdkCustomization/js/client/wrapStoreModules.js
packages/sites/mbio-site/webapp/wdkCustomization/js/client/wrapWdkService.ts
yarn.lock

This branch configures EDA sites to use the current ("legacy") version of UDs rather than VDI. Previous work duplicated the "legacy" version of the `user-datasets` package and named it `user-datasets-legacy` since VDI is being integrated into the `user-datasets` package.

Configure legacy UDs in EDA sites

---

packages/libs/wdk-client/src/Service/Decoders/QuestionDecoders.ts
packages/libs/wdk-client/src/Utils/WdkModel.ts
packages/libs/wdk-client/src/Views/Question/Params/StringParam.tsx

Amend text inputs for string params

---

packages/libs/web-common/src/components/reporters/FastaGeneReporterForm.jsx
packages/libs/web-common/src/components/reporters/SequenceFormFactory.jsx

Minor change to the defline options that changes references to "Gene ID" to be "Unique ID" instead.

Change defline option verbiage

---

packages/libs/eda/src/lib/core/components/computations/Utils.ts

Resolves #804 
During a previous PR I simplified the `isNotAbsoluteAbundance` logic but ended up introducing a bug. Turns out the display name does not include "absolute" ever! Instead of reverting to the previous logic, which still included looking up by display name, this PR uses the hard core collection annotation properties to check if a collection is for absolute abundance. Reminder, those properties are set [here](https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/General/collections/collections.yaml)
I've tested with a metagenomic study, a 16S study, and the FARMM study that has extra funky assays. All look good now 👍 
Third time's a charm!

remove absolute abundance collections via annotations

---

packages/libs/eda/src/lib/core/components/VariableCoverageTable.tsx
packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss

This will address https://github.com/VEuPathDB/web-monorepo/issues/817
The culprit in the ticket's screenshot was a very long variable name without specific separation in words, fructose/glucose/galactose:HIL-neg: Metabolite. So, if we want to keep all table contents inside the table, then we need to use a css, word-break. Screenshot is attached with this PR.
(update) I didn't like the style for Data column so I made some changes. Here is new one:

break word for long variable name for coverage table

---

packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/829.
Although this would work ok, I have a question, @dmfalke. For the second Lin/pathname at Minimize Visualization, I have no idea what the role of computationId is in there. I tried both ClinEpi and Microbiome site to check the value of computationId in there, but it is not that meaningful value for the behavior of the "Minimize Viz": either pass-through or a random word (mbio). So, I think that it can be simply used as the following. What do you think?
`pathname: '../visualizations',`

fix bugs on some EDA viz buttons

---

packages/libs/web-common/src/styles/default-layout.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/styles/home-page-layout.scss

Our breakpoints targeting the grid layout are off. On the live site, notice how changing between the workspace tabs for all datasets to new upload jumps the page:
https://github.com/VEuPathDB/web-monorepo/assets/69446567/8a14a6f6-a6ba-4718-954e-770d605356dd
I reverted an old change I made to `default-layout` that added the `!important` attribute. It was a hack that masked other problems. Somehow it seems Ortho is using just the default layout grid, even on the homepage, without issue.
As for genomics, I made specific changes to breakpoint logic that fixes the original issue that the `!important` attribute aimed to fix, which was the "ghost" effect of the hamburger menu rendering without the site header's background behind it, and it fixed the jumping effect that prompted this …

Fix bug with grid rows and breakpoints

---

packages/libs/eda/src/lib/core/components/computations/Utils.ts
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx

This PR includes changes that let folks see the wgcna data working in the correlations apps.
To run, use jbrestel plasmo backend.
02/02/24 - can select the collections for the correlation app. Found issue on the backend https://github.com/VEuPathDB/microbiomeComputations/issues/81
02/09/24 - all resolved. Data looks good and works!
For testing, please check that there are two collections options in the Correlation (assay x metadata) app.
I've left the Functional Associations correlations app out for now. There are open questions about how to handle that app.

allow wgcna collections in correlation metadata app

---

packages/libs/components/src/map/BoundsDriftMarker.tsx
packages/libs/components/src/map/MapVEuMap.tsx
packages/libs/components/src/map/SemanticMarkers.tsx
packages/libs/components/src/map/animation_functions/geohash.tsx
packages/libs/components/src/stories/MarkerSelection.stories.tsx
packages/libs/eda/src/lib/core/components/layouts/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/options/types.ts
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/appState.ts
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/types.ts

Resolves #432 
Currently branched off #794 
First off, as suggested by Dave months ago, I have moved the event handling of "single click to unselect all" out of MapVEuMap and into SemanticMarkers.  This sets the scene for wiring up selected markers to appState per marker mode (which makes sense, because some marker modes might have no markers!)
<s>Testing the floaters is tricky - there's a performance issue with sample-level variables, and assays are affected by this https://github.com/VEuPathDB/EdaDataService/issues/351 However, for PoC you can make a floating barplot on "continent" and click around to see what happens quite quickly.</s> SOLVED :heavy_check_mark:

Wire marker selection to floaters

---

packages/libs/coreui/src/components/banners/Banner.tsx
packages/libs/eda/src/lib/core/api/DataClient/NoDataError.ts
packages/libs/eda/src/lib/core/api/DataClient/index.ts
packages/libs/eda/src/lib/core/components/visualizations/PluginError.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
packages/libs/eda/src/lib/map/analysis/MapFloatingErrorDiv.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx
packages/libs/http-utils/src/FetchClient.ts

Depends on https://github.com/VEuPathDB/EdaDataService/pull/328
Resolves #606  
Resolves #607
Resolves #571
In the map, a "no data" response will render a warning banner. To do so, I tweaked the `MapFloatingErrorDiv` to accept `children` as a means to customize its content. Screenshot below:
I've also added the `Banner` component with `type: warning` to the `PluginError` messaging as shown:

Handle 204s in DataClient and FetchClient

---

packages/libs/coreui/src/components/banners/Banner.tsx
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx

Resolves #844 
Still uses `Banner` but I added a `hideIcon` prop and changed the banner type to `normal`, which uses a gray background.

Add hideIcon prop to Banner and use for visibleHelp attribute banner

---

packages/libs/eda/src/lib/core/components/computations/plugins/Plugins.scss
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/832.
For the last item to fix a bug or change behavior, honestly, I could not fully understand how the computation worked, but I managed to make it fix anyway 😅 
Some screenshots after changing:

modifying correlation inputs

---

packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
packages/libs/eda/src/lib/core/types/general.ts

This will address https://github.com/VEuPathDB/web-eda/issues/1631.
Following on from some changes in back end responses (see #836) we are revisiting the behaviour of floating plots when there is nothing to plot. A key background point here is that the SAM floating plot endpoints (e.g. histogram, lineplot etc) don't return `completeCasesAllVars` and `completeCasesAxesVars` for performance reasons and because missing data is not handled the same as in EDA. These two values are used to calculate `outputSize` which is fed to `PluginError` to produce an appropriate warning banner when it is zero.
In addition we have relaxed `io-ts` validation to allow nulls for binSlider and binSpec when there is an empty response from the back end (but no 204 or 500). This happens when there is a subset, but …

nicely handle empty data for visualizations in SAM

---

packages/libs/coreui/src/components/Mesa/Ui/HeadingCell.jsx
packages/libs/wdk-client/src/Service/Decoders/RecordClassDecoders.ts
packages/libs/wdk-client/src/Utils/WdkModel.ts
packages/libs/wdk-client/src/Views/ResultTableSummaryView/ResultTable.tsx

Depends on https://github.com/VEuPathDB/WDK/pull/80
This is the client work for #838

Allow html in result table column tooltips

---

packages/libs/eda/src/lib/core/components/filter/HistogramFilter.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/853. As Dave said, marginLeft: -1em looks similar to the Live site's position

reset button position for histogram filter

---

packages/libs/components/src/map/BoundsDriftMarker.tsx
packages/libs/components/src/map/styles/map-styles.css
packages/libs/eda/src/lib/map/analysis/SubStudies.tsx
packages/libs/eda/src/lib/map/analysis/appState.ts
packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts
packages/libs/eda/src/lib/map/analysis/mapTypes/MapTypeHeaderStudyDetails.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/types.ts

closes #854
This PR addresses UX feedback:
- Reduce default size of study panel
- Update header verbiage:
- "Showing: 440,305 samples from 5 studies"
- "Selected: 1,234 samples from 2 studies"
- Use CTRL-CLICK
- Remove opacity from marker on hover
Note that in addition to removing opacity from markers on hover, I also made the bounding rectangle appear above the marker. This makes that rectangle visible when smaller than the marker, and easier to see in general. The rectangle is also non-interactive, so it does not impede the ability to click on the marker, nor does it interfere with the popup.

SAM study details ux followup

---

packages/libs/wdk-client/src/Views/User/Password/ChangePasswordLink.jsx
packages/libs/web-common/src/externalLinkHandler.ts
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

This PR removes the target attribute from tools. If a link already has a target attribute, then its behavior will not change. This allows us to force external links to open in the same browser.

More external link handling

---

packages/libs/eda/src/lib/map/analysis/mapTypes/MapTypeHeaderStudyDetails.tsx

This was suggested at a recent map ux meeting. I think it makes sense.

Make "### Studies" a link and remove button from tooltip

---

packages/libs/eda/src/lib/core/api/DataClient/index.ts

Fixes #866 
This fixes one of the runtime exceptions when the back end `eda-service/filter-aware-metadata/continuous-variable` returns null and a 204.  However, it really makes a difference where you make the timeslider filter.
Here is where it causes a 204 and is now fixed in this PR.  In a comment below I'll demonstrate a 500 that probably needs fixing on the back end.

Intercept nulls in another place and refactor

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/controllers/FastaConfigController.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/DynSpansBySourceId.scss

This PR fixes a styling issue:
**Before**
**After**
It also adds a banner to SRT:

Genomic segments: Fix styling of input labels and add banner for SRT

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/controllers/FastaConfigController.tsx

Update verbiage about genome-scale downloads

---

packages/libs/eda/src/lib/core/components/computations/RunComputeButton.tsx
packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx

We've have a run around with the correlation app names. We finally agreed on calling them both "Correlation" and using parentheticals to distinguish between the two. That seemed really nice on the new visualization page and on the thumbnail page but today i realized the actual viz page looks like this with parentheses all over the place. Yuck!
This PR removes parentheses and the text they contain from the Generate Results button and the titles of Steps 2 and 3.
Would really love to get this in for b67 if anyone is around!

remove parentheticals from Steps 2-3 in computes

---

packages/libs/eda/src/lib/core/components/computations/RunComputeButton.tsx
packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
packages/libs/eda/src/lib/core/utils/string-formatters.ts

Discussed in #878 , we repeated ourselves _three_ times!!! It's function time!
This PR adds `removeParentheticals` and `replaceParentheticals` to our util functions. The former just strips out the parentheticals and surrounding whitespace from a string. The latter replaces that parenthetical+white space with a new string. This latter one isn't used yet but it seemed an obvious extension so I thought I might as well go ahead and add it.

add remove or replace parentheticals utils

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

This PR fixes opacity issues related to scatter vs scattergl
**Before**
**After**

Fix opacity for ci for scatter vs scattergl

---

packages/libs/wdk-client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts

Fixes #888 
This PR clears any error message related to fetching an ontology summary.

Clear errorMessage when a new ontology summary is loaded

---

packages/libs/wdk-client/src/Views/Question/Params/TreeBoxEnumParam.tsx

This PR fixes an issue where "single pick" treebox params are including branch leaves in the selection.
The following changes were made:
1. Use `parameter.maxSelectedCount` help determine if a parameter is multiPick. This is only does for UI purpose, as the format of the param value varies based on if it's multiPick.
2. If a treeBox parameter is not multiPick, do not include branch leaves in the value. It's not clear why we include the branch nodes when all children are selected, but we can investigate that at a later time.

Use maxSelectedCount to test if multiPick, and do not include branches if not multiPick

---

packages/libs/web-common/src/App/NewsSidebar/News.scss
packages/libs/web-common/src/components/TwitterTimeline.jsx

Resolves #870
Screenshot in strict mode, script doesn't initialize:
Screenshot when script does initialize:

Condition warning message to log into twitter if script initializes

---

packages/libs/user-datasets/src/lib/Components/UploadForm.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetNewUploadController.tsx
packages/libs/user-datasets/src/lib/Utils/types.ts
packages/libs/user-datasets/src/lib/Utils/upload-config.tsx
packages/libs/wdk-client/src/Components/InputControls/FileInput.tsx
packages/libs/wdk-client/src/Utils/Converters.ts

fixes #915 
This does not affect files upload via URL, do large files can still make it to the installer.
Here is a screencast with the new feature:
[Screencast from 2024-03-08 12-26-14.webm](https://github.com/VEuPathDB/web-monorepo/assets/365139/7e41ea98-232f-4f9d-b8b2-d2c048ad246c)

Add support for max file size

---

packages/libs/coreui/src/components/Mesa/Ui/DataRow.jsx
packages/libs/coreui/src/components/Mesa/Ui/HeadingRow.jsx
packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
packages/libs/web-common/src/styles/client.scss
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/GroupRecordClasses.GroupRecordClass.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/SequenceRecordClasses.SequenceRecordClass.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/utils.tsx

Works to resolve issues found in https://github.com/VEuPathDB/web-monorepo/issues/921
Specifically, this branch does the following:
- fix Bob's discovery re: "eventHandlers undefined" issue in his orthotree branch
- fix ortho's accession column issues w/ links (previously thought this would be handled in the model by adding `type="link"` somewhere, but is client-side instead)
- fix issue with the `wrappedChildRow` logic breaking w/ classes only in production bundle (removed faulty function check)
- pass props to Mesa to enable row counts
- define column width for childRow toggle columns

Data table followup work

---

packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.scss
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx

This PR adds a group description to the show-hide WDK parameter group section. It also includes some styling changes: use `h4` for parameter names, and lighten the background of the show-hide section.
The styling could probably use some work, but I thought this would be a good starting point.
---
**Before**
---
**After**
closes #930

Add group description to show-hide group

---

packages/libs/web-common/src/components/SiteSearch/SiteSearch.scss
packages/libs/web-common/src/components/SiteSearch/SiteSearch.tsx

Limit site search titles to one line and add title attribute

---

packages/libs/eda/src/lib/core/api/AnalysisClient.ts
packages/libs/eda/src/lib/core/types/analysis.ts
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/web-common/src/controllers/LegacyMapRedirectHandler.tsx
packages/libs/web-common/src/routes.jsx
packages/libs/web-common/src/styles/client.scss

Wire up redirect from legacy map to new map

---

packages/libs/components/.storybook/main.js

This PR fixes an issue with storybook stories in `@veupathdb/components`.
Several map stories, and all network stories, have been failing with a `React is not defined` error. I believe it is related to adding the `@emotion/babel-preset-css-prop` to the end of the list of babel presets. The `@babel/preset-react` automatically adds `import React from 'react'` to modules. If `@emotion/babel-preset-css-prop` introduces a reference to `React` to a module, this would explain the error, since `@babel/preset-react` has already run. 
Moving it to the beginning fixes the issue.

change order of babel presets

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/961. Implementation didn't take too much time but tests did 😅. Changed both HistogramViz and Lineplot Viz: time series worked just fine after changing Lineplot Viz. 
One note is that backend did return incorrect binWidthRange for the example case in the ticket (please see the screenshot below), { min: 0.1, max: 0 }. @d-callan? 
Here are some screenshots with this PR:

set default binWidth as undefined for HistogramViz and Lineplot Viz

---

packages/libs/coreui/src/components/buttons/SwissArmyButton/index.tsx
packages/libs/eda/src/lib/core/types/study.ts
packages/libs/eda/src/lib/workspace/DownloadTab/CurrentRelease.tsx
packages/libs/eda/src/lib/workspace/DownloadTab/MySubset.tsx
packages/libs/eda/src/lib/workspace/DownloadTab/StudyCitation.tsx
packages/libs/eda/src/lib/workspace/DownloadTab/index.tsx

Resolves #989
Resolves #927
Note that I've amended the logic to only display this verbiage in ClinEpiDB for non-user studies. Otherwise, this verbiage won't display in MicrobiomeDB or genomics sites irrespective of its `isUserStudy` status.
I also took a chance to clean up some of the styling. I didn't like how I handled the spacing via margins so set the container to be flex and used gap instead.
MicrobiomeDB:
User study in ClinEpiDB:
Curated study in ClinEpiDB:

Condition data access verbiage in download tab wrt projectDisplayName && isUserStudy

---

packages/libs/wdk-client/src/Controllers/RecordController.tsx
packages/libs/wdk-client/src/Views/Records/RecordNotFound.css
packages/libs/wdk-client/src/Views/Records/RecordNotFoundPage.tsx

Responds to feedback [here](https://github.com/VEuPathDB/web-monorepo/pull/944#issuecomment-2030331134) and in a slack thread. Screenshots below show how the UIs compare between no record and empty search results.
**No record found**
**No search results**

Make adjustments to record not found UI

---

packages/libs/wdk-client/src/Service/Decoders/QuestionDecoders.ts
packages/libs/wdk-client/src/Utils/WdkModel.ts
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx

Depends on https://github.com/VEuPathDB/ApiCommonModel/pull/42 and https://github.com/VEuPathDB/WDK/pull/86
Renders a question-level help banner above the `ParameterList`.

Consume and display question's new searchVisibleHelp attribute

---

packages/libs/coreui/src/components/banners/Banner.tsx
packages/libs/wdk-client/src/Service/Decoders/QuestionDecoders.ts
packages/libs/wdk-client/src/Utils/WdkModel.ts
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.scss
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx

Depends on the second commit in https://github.com/VEuPathDB/WDK/pull/86 that adds `visibleHelpPosition` as an optional attribute to params.
A `visibleHelpPosition: 'right'` would display as shown:

Update param UI to reflect visibleHelpPosition set to 'right'

---

packages/libs/web-common/src/bootstrap.js

Fixes #1004
This PR removes double and trailing slashes from URLs, when the client application starts up.

Remove double and trailing slashes

---

packages/libs/web-common/src/components/homepage/Header.tsx

Resolves issue where submenus are disappearing unless a click event occurs.
From slack:
- https://epvb.slack.com/archives/C01DS6HBY3Z/p1713193639600269
- https://epvb.slack.com/archives/GBDR4LDNC/p1712673496607519
NOTE: this issue is occurring on live sites

Pass noop dismissSubmenus callback to sub-submenus

---

packages/libs/components/src/plots/BipartiteNetwork.tsx

Using real links allows users to open the link in a new tab with ctrl-click or right-click, etc.
closes #1007

Use real links

---

packages/libs/eda/src/lib/workspace/Subsetting/SubsetDownloadModal.tsx

Resolves #949
Uses same UI/banner that prevents table previews for entities with 1000 or more variables.

Prevent table previews for UDs in download modal

---

packages/libs/eda/src/lib/core/utils/geoVariables.ts
packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BubbleMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/PieMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/appState.ts
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx

Fixes #1024 
This only affects the Transmission Zero Field Trials prototype dataset at the moment (qa restricted clinepi) because this is the only study where more than one entity has geo variables.
Luckily a lot of the code was already passing around `geoConfigs` rather than `geoConfigs[0]` so there wasn't a huge amount of upheaval.
I have implemented this as if there was a drop-down for the user to choose the geoEntity they wanted, but instead have chosen the least ancestral entity for them automatically. So this is why this "choice" is stored in appState. We can add UI later if needed.

Markers automatically use the most appropriate geoEntity when there are multiple to choose from

---

packages/libs/eda/src/lib/workspace/EDAWorkspaceHeading.tsx

Reverts VEuPathDB/web-monorepo#1003
This logic is not correct. If anything, we only want to show the button if a study has any access restrictions.

Revert "Only show Management Dashboard button for user datasets"

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/selectorIcons/HistogramTimelineSVG.tsx

Resolves #1025 
New viz icon added! Here's an example of how it will look next to all the other icons:

add timelinehisto viz icon

---

packages/libs/eda/src/lib/core/components/computations/Utils.ts
packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
packages/libs/eda/src/lib/core/components/visualizations/OutputEntityTitle.tsx
packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss
packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx
packages/libs/eda/src/lib/core/types/study.ts

Resolves #382 and #898 and [comment](https://github.com/VEuPathDB/web-monorepo/issues/393#issuecomment-1658447748) 
First we added `member` and `memberPlural` as annotations for `CollectionVariableTreeNode`. Then we used those annotations to clarify collection filters, and add better info to the volcano visualization. One side effect was that to better position the subtitle for the `OutputEntityTitle`, I moved the `<br>` inside the component and modified the css.

Add member type to legends, subtitles, and collection logic

---

packages/libs/eda/src/lib/core/utils/study-records.ts
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx
packages/sites/genomics-site/webpack.config.local.mjs

Hides datasets with `is_public=false` from mapveu menu
Depends on https://github.com/VEuPathDB/EbrcModelCommon/pull/47
Those w/ `is_public=false` will have an icon on sites with `showUnreleasedData=true`:

Eda genomics map menu items

---

packages/libs/web-common/src/components/homepage/Header.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

Resolves https://redmine.apidb.org/issues/53433 and removes "new" images from `Sequence retrieval` and `MapVEu` menu items.

Open help menu details by default, remove new images

---

packages/libs/components/src/map/AreaSelectHack.js
packages/libs/components/src/map/styles/map-styles.css

This was branched out from https://github.com/VEuPathDB/web-monorepo/pull/1041. 
Yellow dot-line are less visible than blue dot-line, perhaps due to the background color of gray (with 50% opacity), but it may be okay? Tried green one, just out of curiosity, and it may have better visibility than yellow (screenshot): but this PR is for yellow. Perhaps you can try to change color at the CSS's border. 
If it is good enough, then I will merge it into the parent PR and then merge the parent PR which was already approved.

styling area selection box

---

packages/libs/components/src/plots/BipartiteNetwork.tsx

I noticed that the gray were sitting above the higlighted edges. Turns out it was a very simple fix!
Voila!
https://github.com/VEuPathDB/web-monorepo/assets/11710234/87f4115d-dee6-4675-be92-ced8fee69115

draw highlighted edges atop gray edges

---

packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx

Fixes #896 
The problem for both donut/bar and bubble markers was that `useMarkerData` was calling either `useDistributionOverlayConfig` or `useLegendData` internally using the `filters` that was passed to it. Problem was that we were sending filters plus "little filters for marker data" (aka viewport and timeslider).  This meant that the `overlayConfig` (or `legendData`) needed for the marker requests (and/or processing) was not the same as has been used for the legend (which didn't use any little filters).
As explained in #896 this was most obvious when showing the timeslider variable on the markers. The legend and markers were telling completely different stories.
Now the code is slightly more verbose because `useDistributionOverlayConfig` or `useLegendData` are called outside …

Don't send little filters to `useDistributionOverlayConfig` and `useLegendData`

---

packages/libs/eda/src/lib/workspace/EDAWorkspaceHeading.tsx
packages/libs/eda/src/lib/workspace/StandaloneStudyPage.tsx
packages/libs/eda/src/lib/workspace/WorkspaceRouter.tsx

Addresses the issue raised in this slack thread: https://epvb.slack.com/archives/C01DS6HBY3Z/p1714659198160189.
**Before**
**After**

Include `isStudyExplorerWorkspace`  for standlone study page

---

packages/libs/components/src/components/plotControls/TimeSlider.tsx

This is a test to consider the inherent timeSlider's offset, 2 pixels.

testing timeSlider offset

---

packages/libs/eda/src/lib/core/components/computations/plugins/correlation.tsx

Closes #1078
This PR makes it so the WDK search links in WGCNA EDA correlation viz use the correct url prefix. The url prefix is derived from the host website (not to be confused with HostDB website). This means the links will likely not work on dev sites, unless the same dev site prefix exists for both plasmodb and hostdb.
In the future, this could be driven by configuration values.
_**The production site needs to be patched with this change.**_

Fix search links for WGCNA network nodes

---

packages/libs/wdk-client/src/Utils/diyDatasets.ts

This PR fixed an issue where dataset ids were converted to `NaN`.
Context: https://epvb.slack.com/archives/CBE520QUC/p1715277949886819

Remove call to `Number`

---

packages/libs/components/src/plots/Barplot.tsx

This will possibly address https://github.com/VEuPathDB/web-monorepo/issues/1101. I have looked at the current implementation of Barplot Viz but couldn't find specific issue why it was caused. Then, tested with some mock-up data that consists of a mixture of number strings and text strings like the screenshot, Surprisingly, it seems like bar chart at Plotly treats those specific case as number strings only, by excluding text strings. 
That being said, I found an option that the x-axis (technically independent axis) can always be treated as categorical values, by setting type: 'category'. From my tests (using codesandbox.io), it accepts such mixed strings correctly. 
So, @bobular it would be great if you can test this PR with the user dataset you mentioned.

possibly address barplot x-axis with a mix of number strings and text strings

---

packages/libs/wdk-client/src/Service/ServiceBase.ts

This PR fixes an issue where the reload dialog would appear on an initial page load.
The issue is due to some requests being made before the WdkService `startupTime` property is initialized (as the variable `_version`) on the client. Such requests would set `_hasRequestBeenMade` to `true`, but the request would not include the header `x-client-wdk-timestamp`.
The fix is to always call `_initializeStore` before any requests are made. This took a little refactoring to avoid an infinite loop.

Wdk service cache fix

---

packages/libs/user-datasets/src/lib/Actions/UserDatasetsActions.ts
packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.scss
packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.jsx
packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.scss
packages/libs/user-datasets/src/lib/Components/UploadForm.tsx
packages/libs/user-datasets/src/lib/Components/UserDatasets.scss
packages/libs/user-datasets/src/lib/Components/UserDatasetsWorkspace.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetListController.tsx
packages/libs/user-datasets/src/lib/Controllers/UserDatasetRouter.tsx
packages/libs/user-datasets/src/lib/StoreModules/UserDatasetDetailStoreModule.ts
packages/libs/user-datasets/src/lib/StoreModules/UserDatasetListStoreModule.ts
packages/libs/user-datasets/src/lib/Utils/types.ts
packages/libs/web-common/src/component-wrappers/AnswerController.scss
packages/libs/web-common/src/component-wrappers/StudyAnswerController.jsx
packages/libs/web-common/src/hooks/diyDatasets.ts
packages/libs/web-common/src/hooks/diyStudySummaries.tsx
packages/sites/clinepi-site/webapp/js/client/component-wrappers/AnswerController.jsx
packages/sites/clinepi-site/webapp/js/client/component-wrappers/AnswerController.scss
packages/sites/clinepi-site/webapp/js/client/component-wrappers/SiteHeader.jsx
packages/sites/clinepi-site/webapp/js/client/data/headerMenuItems.jsx
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/gene-list-export-utils.tsx
packages/sites/mbio-site/webapp/wdkCustomization/js/client/component-wrappers/index.js
packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx

This PR adds the ability to make a user dataset public. This is done by setting the new `visibility` property introduces by VDI.
_This feature is only visible on clinepi and mbio sites_.

Add ability to make user datasets public (aka, community datasets)

---

packages/libs/components/src/components/tidytree/TreeTable.tsx
packages/libs/coreui/src/components/Mesa/Ui/DataCell.jsx
packages/libs/coreui/src/components/Mesa/Ui/DataRow.jsx
packages/libs/coreui/src/components/Mesa/types.ts

Note this targets the ongoing orthogroup branch.
The default Mesa behaviour when `options.inline` is `true`, is for cell contents to be truncated so the rows are equal height. Clicking on the rows expands them to show the full contents.
This wasn't acceptable for ortho, where the tree and table alignment is messed up by expanding rows. (Also browser scroll-to behaviour is unpredictable and you can't easily find the row you expanded.)
With this PR there's a new configuration option: `inlineUseTooltips` which removes the click behaviour and adds tooltips to all table cells.
It would be nice to do this for
a) only cells with content
b) only cells that overflow
but neither are economical to implement at this time.

New optional Mesa inline table behaviour using tooltips

---

packages/libs/eda/src/lib/core/components/FilterChipList.tsx

This PR renders EDA filters with invalid variable references, so that they can be removed from an analysis. A tooltip in included, explaining why the filter is invalid.

Display invalid filters so they can be removed

---

.github/workflows/npm-publish-sites.yml

git tag `v1.2.3` -> npm tag `latest`
git tag `v1.2.3-someword` -> npm tag `someword`
git tag `v1.2.3.anotherword.3` -> npm tag `anotherword`
falls back to `latest` if the pattern matching fails for whatever reason.

Add more control over npm tags

---

packages/libs/eda/src/lib/core/components/visualizations/implementations/NetworkVisualization.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/selectorIcons/BipartiteNetworkSVG.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/selectorIcons/NetworkSVG.tsx

Resolves #1109 
Adds network viz selector icon. Also cleans up a little old code from the bipartite selector icon.

add network selector icon

---

packages/libs/user-datasets/src/lib/Components/Detail/BigwigDatasetDetail.jsx

Fixes #1117
This PR addresses two issues with RNA-Seq datasets:
1. Prevents a WDK search request when dependencies are not yet installed.
2. Prevents non-bigwig files from appearing in the **Genome Browser Tracks** table
When addressing the first issues, I noticed that it's feasible for there to be multiple genomic dependencies, but the code does not account for it. It will always use the last one in the array. It's possible that this will never happen in the real world, but it might be worth asking about. I will post a question on slack.

Userdatasets rnaseq fixes

---

packages/libs/eda/src/lib/core/components/EDAAnalysisListContainer.tsx
packages/libs/eda/src/lib/core/components/EDAWorkspaceContainer.tsx
packages/libs/eda/src/lib/core/hooks/promise.ts
packages/libs/eda/src/lib/core/hooks/study.ts
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx

fixes #1131 
This PR adds options to `usePromise`, allowing for more control over its behavior. This allows us to force the `value` property of the hook's return value to be `undefined` when it is in a pending state. It also allows us to force errors to be thrown.
These changes provide a more declarative interface, preventing unintentional bugs.

Eda study data race condition

---

packages/libs/eda/src/lib/core/components/EDAAnalysisListContainer.tsx
packages/libs/eda/src/lib/core/components/EDAWorkspaceContainer.tsx
packages/libs/eda/src/lib/core/hooks/promise.ts
packages/libs/eda/src/lib/core/hooks/study.ts
packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx

* Add options to usePromise hook
* Use new options of usePromise hook, to prevent inconsistent data
* Return the `value` property of `usePromise` result
(cherry picked from commit f2a73f9ea289dadecb684b8a1e2041b1d54aca4a)

Eda study data race condition (#1132)

---

packages/libs/eda/src/lib/workspace/DownloadTab/index.tsx
packages/libs/eda/src/lib/workspace/EDAWorkspaceHeading.tsx
packages/libs/eda/src/lib/workspace/StandaloneStudyPage.tsx

This PR adds a "Download" tab to standalone study pages in EDA

EDA: standalone downloads

---

packages/libs/eda/src/lib/core/hooks/promise.ts

fixes #1136
This PR fixes the semantics of `throwError` such that the error can be caught by the caller of `usePromise(..., { throwError: true })`.

Throw synchronous error in usePromise context, if `throwError` is `true`.

---

packages/libs/eda/src/lib/core/hooks/promise.ts

Throw error in usePromise context, instead of in Promise context. (#1135)
(cherry picked from commit a8006606241e56a01a8c24bede0c9c628fcb94fc)

Merge fix for new UD in ClinEpi

---

packages/libs/components/src/components/tidytree/HorizontalDendrogram.tsx
packages/libs/components/src/components/tidytree/TreeTable.tsx
packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx
packages/libs/coreui/src/components/inputs/checkboxes/CheckboxList.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/RecordTable_TaxonCounts_Filter.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

This PR introduces table filters to the tree table section of group pages. There are three filters: pfam domains, core/peripheral, and species.
The first two filters are applied after the popover is dismissed, while the third one is applied immediately. This is a bug, as the intended behavior is to apply the selection after the popover is dismissed. **Question: Which behavior is preferable?** 
Here is a screenshot:

Orthogroup tree table  pfam filter

---

packages/libs/web-common/src/components/Announcements.jsx
packages/sites/clinepi-site/webapp/js/client/data/headerMenuItems.jsx
packages/sites/mbio-site/webapp/wdkCustomization/js/client/component-wrappers/index.js

fixes #1149
This PR changes the order of study menu items. It also adds a banner for PRISM2 Border Cohort.

Eda menu and banner

---

packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx

fixes #1151
The PR adds details if a dataset is visible to the community.
For example:
> Are you sure you want to delete this study? It will no longer be visible to the community, and 1 collaborator you've shared with will lose access.

Include details in confirmation message that dataset will no longer be visible to the community

---

packages/libs/eda/src/lib/core/components/variableSelectors/VariableList.tsx
packages/libs/eda/src/lib/core/components/variableSelectors/hooks.ts
packages/libs/eda/src/lib/core/types/study.ts
packages/libs/eda/src/lib/core/utils/wdk-filter-param-adapter.ts

Resolves https://github.com/VEuPathDB/web-monorepo/issues/1094
New version in context:

1094 reorganize featured variables

---

packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.jsx

Resolves #1148
A couple notes:
1. I don't have an ortho dev site to run these changes on to ensure the actual POST works, but it's wired up very similarly to the genomics version that works.
2. I can make the model change to change the isDisplayable flag (or whatever it's actually called in the XML) of the clusterInput column if you think it's worth doing; again, not sure what the future of this UI is with respect to the tree diagram.

Refactor OrthoMCL's Sequences table to enable Mesa's selection column

---

packages/libs/coreui/src/components/inputs/SelectList.tsx
packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Note that this targets `orthogroup-tree-table`, so can be merged without review.
Maybe we demo both or make a video with both?

Instant filters for the orthogroup page

---

packages/libs/components/src/plots/Node.tsx

This will address https://github.com/VEuPathDB/web-monorepo/issues/1165. 
@asizemore Simply put, it was a typo, though it took some time to find the reason as it was hard to notice 😓

set cursor pointer for network node label

---

packages/libs/components/src/components/widgets/RadioButtonGroup.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotMarkerConfigurationMenu.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerConfigurationTable.tsx
packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/PieMarkerConfigurationMenu.tsx

Fixes #1167 
Before / After
(tooltip is `This option is currently disabled for maintenance reasons`)
Before / After (notice the removal of an all-disabled "Marker X-axis controls" section)
Before / After

Add tooltip reasons for disabled RadioButtonGroup options and style Map marker configuration panel a bit better

---

packages/libs/eda/src/lib/workspace/PublicAnalysesRoute.tsx

Prevents the temporary "Unknown Study" name appearing while dataset records are loading:
https://github.com/user-attachments/assets/80e15d5d-49a6-4967-8ded-135c79172e42

Wait for all content to load before rendering

---

packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx

Here's the phyletic distribution back at the top of the page. Species filter-drop down still works as before!

Restore the buttonless phyletic distribution

---

packages/libs/eda/src/lib/workspace/DownloadTab/Downloads.tsx

The verbiage about a study not having data is confusing. This PR removes it. This PR also renders a loading spinner until all data needed for the section is loaded.

Modify status verbiage: remove "no files" and hoist loading

---

packages/libs/wdk-client/src/Actions/UserActions.ts
packages/libs/wdk-client/src/Utils/Errors.ts
packages/libs/wdk-client/src/Utils/Json.ts

This PR fixes how validation bundle errors are handled. We were passing the Error object to the `ok` function from the `JSON` module, which expects a parsed json object. This PR addresses that by first parsing `error.response`, and then passing that parsed value to the `ok` function. It also moves the checks to the `clientError` block, which is when we would expect a validation bundle error.
This can be tested by attempting to register a new user using an email address associated with an existing user. The validation error should be unpacked from the validation bundle and displayed as a human-readable message:

Fix how validation bundle error responses are handled

---

packages/libs/coreui/src/components/Mesa/Ui/RowCounter.jsx
packages/libs/coreui/src/components/Mesa/style/Ui/TableToolbar.scss
packages/libs/wdk-client/src/Views/Records/RecordTable/RecordFilter.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Ortho table tweaks for OMCL7

---

packages/libs/wdk-client/src/Service/ServiceBase.ts
packages/libs/wdk-client/src/StoreModules/UnhandledErrorStoreModule.ts

fixes #1216
This PR addresses an issue where errors are thrown when the client is clearing the data cache store and reloading the page. 
Changes include:
- Move a return statement outside of an if-block
- Expose `_isInvalidating` and use that to suppress the error modal.

Fix issue with how a 409 response from the WDK service is handled

---

packages/libs/web-common/src/components/JbrowseIframe.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Jbrowse.tsx

Fixes #1224
This PR adds a referrerPolicy that disabled the referrer header for jbrowse iframes.

Do not include referrer for jbrowse iframe, and address linting warnings

---

packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx

Pass the `type` property to `getDetailView`. This fixes a bug where custom views are not being used.

remove typeof operator

---

packages/libs/wdk-client/src/Core/Root.tsx

This will improve perceived page load time, since we don't have to wait for the wdk service to return the user object before rendering the page.

Use bearer token to check if user is guest

---

packages/libs/wdk-client/src/Core/Root.tsx
packages/libs/web-common/src/components/records/Sequence.tsx

This PR changes the global click handler in Root.tsx so that the browser will handle links that only contain a hash (eg, `<a href="#foo">Go to page section.</a>`).

Handle hash change

---

packages/libs/coreui/src/components/inputs/checkboxes/CheckboxTree/CheckboxTree.tsx
packages/libs/coreui/src/hooks.tsx
packages/libs/coreui/src/index.ts
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Interestingly this works pretty much as expected - the filter checkboxes update way before the table is rerendered. Unclicking them is the same.
All in all it's a better UX... except... when the organism filter is filtered using the text search, e.g. for 'gam'.  Then when you click on the Anopheles gambiae Pest checkbox, the behaviour is OK, but when unchecking the same box the checkbox doesn't update until the tree-table has updated. If the text search is cleared and the same checkbox is unchecked, it unchecks fairly quickly, as intended. I wonder what's going on?
Note, we could encapsulate the `useState` and `useDeferredValue` with something like this:
```
import { useState, useDeferredValue } from 'react';
function useDeferredState<T>(initialValue : T) : [T, T, …
```

use `useDeferredValue` to improve responsiveness of filter checkboxes 

---

packages/libs/coreui/src/components/buttons/PopoverButton/PopoverButton.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

<s>There's an edge case where say you are filtered on 6 proteins and you select-all 6 proteins and then click "refine filter" the filter widget doesn't close automatically (because our `key` doesn't change)</s> Solved :heavy_check_mark:

Orthogroup tree table  protein filter

---

packages/libs/multi-blast/src/lib/utils/wdkServiceIntegration.ts

This PR removes the multi-blast input query from requests to `/refreshed-dependent-params`. Note that this also affects the revise form for individual query steps. Remove the value does not impact the response, since it is not part of the dependency chain.

Override wdkService methods to omit the blast input query from WDK service requests

---

packages/libs/coreui/src/components/inputs/SelectList.tsx
packages/libs/coreui/src/components/inputs/checkboxes/CheckboxList.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Resolves #1254 
I looked into improving the responsiveness of the table paging controls with useDeferredState, but it was not possible due to the memoisation of `mesaState` - which has a mix of "slow" and "volatile" dependencies. I wonder if that memoisation isn't actually necessary? (Answer: I removed it and this reintroduced the janky search field checkboxes...)

Orthogroup tree table  1254 fixes

---

packages/libs/eda/src/lib/core/components/visualizations/InputVariables.tsx
packages/libs/eda/src/lib/core/utils/data-element-constraints.ts

This PR addresses cases where a selected variable for an EDA viz is no longer available (for example, due to data being reloaded).
Here is an example illustrating the current UX: https://microbiomedb.org/mbio/app/workspace/analyses/lkrccJY/import. Go to visualizations, and select the first one to see the current UX.
This screenshot illustrates the new UX:

EDA viz - handle invalid variable selections

---

packages/libs/wdk-client/src/Views/Question/Params/TypeAheadEnumParam.tsx

Prevent form submission when pressing enter in typeahead input, and remove 3-character limit for showing options.

Fix WDK typeahead form submission bug

---

packages/libs/web-common/src/routes.jsx

This PR removes the hash of the current location from the `url` prop of `ExternalContentController` used for static-content. Including the hash causes page updated whenever the hash changes, which is not desirable.

Remove hash from url for static content, to make page more stable

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/common/RecordTableContainer.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx

This PR updates genomics-site to use tableState from wdk-client. There is some additional logic in genomics-site that persists which row of a table is opened. If we want to retain this state, it should be on a pre-record basis.

Use tableState from wdk-client

---

packages/libs/multi-blast/src/lib/components/BlastJobError.tsx
packages/libs/multi-blast/src/lib/components/BlastWorkspaceResult.tsx
packages/libs/multi-blast/src/lib/utils/api.ts

This PR adds any available error message for failed blast jobs:

Multi blast job error

---

packages/libs/coreui/src/components/Mesa/Components/AnchoredTooltip.jsx
packages/libs/coreui/src/components/Mesa/Ui/DataTable.jsx
packages/libs/coreui/src/components/Mesa/Ui/ExpansionCell.tsx
packages/libs/coreui/src/components/Mesa/Ui/HeadingCell.jsx
packages/libs/coreui/src/components/Mesa/style/Cells.scss
packages/libs/coreui/src/components/Mesa/style/Ui/DataTable.scss
packages/libs/coreui/src/components/Mesa/style/Ui/HeadingCell.scss
packages/libs/wdk-client/src/Views/Question/Params/FilterParamNew/FilterParam.css
packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.css
packages/libs/web-common/src/styles/client.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/Downloads/Downloads.scss
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/GroupRecordClasses.GroupRecordClass.scss

This PR addresses some recently introduced layout issues with Mesa table, specifically when rows are either selectable or expandable.
With the relatively recently `position: sticky` css value, we can dramatically simplify the html and remove a decent amount of runtime javascript.
These changes impact all uses of Mesa table:
- Dataset and study pages
- Strategy results
- Record page tables
- EDA categorical filters
- TreeTable (ortho group record's protein table)
Seeing as this is an urgent fix (the bug is on production), I would appreciate a quick review. I'm happy to go over changes in more detail, after this is merged.

Mesa fix layout

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx

This gives developers more flexibility with how content is rendered in the top section of the record page, including using table attributes for the overview properties.

replace record_overview attribute with react component on gene page

---

packages/libs/components/src/stories/plots/ScatterPlot.stories.tsx
packages/libs/components/src/stories/plots/ScatterPlot.storyData.ts
packages/libs/components/src/types/plots/addOns.ts
packages/libs/eda/src/lib/core/api/DataClient/types.ts
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Resolves #1322 
This was a little funky because plotly already allows for highlighting - we just have to set the color appropriately in the trace! So this PR is more of a hijack of our current processing of scatterplot data to recolor the points.
A few considerations:
- Should the backend just break up the data into highlight and non-highlight for us? It could, and would basically add another "overlay"-type column, but the issue is when we highlight a scatterplot with anything that we have calculated. Smoothed means, best fit line, etc. Breaking up the data for highlgihting would move these points to a place that doesn't correspond with their place in a calculation. We don't want a highlight-smoothed mean and a non-highlight-smoothed mean, we would just want one smoothed mean with a few …

Add ability to highlight points to scatterplot

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/utils.js
packages/sites/genomics-site/webapp/wdkCustomization/js/client/types/aiExpressionTypes.ts

This is branched off `ai-expression` #1330

AI expression topics overhaul

---

ARCHITECTURE.md
BUILD.md
FEATURES.md

An attempt to capture the high-level workings of our websites

High level documentation

---

packages/libs/user-datasets/src/lib/Components/UploadForm.tsx

Uploads via URLs were broken in MBio - [slack thread](https://epvb.slack.com/archives/CBLPK9ZD3/p1741789394225579) 
Fix seems likely to work.  See https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol

Fix UD upload form via URL - added colons to protocol strings

---

packages/libs/web-common/src/components/EdaDatasetGraph.tsx
packages/libs/web-common/src/components/eda/EdaScatterPlot.tsx

Adds a plot title to the EDA scatter adaptor. The plot title nicely comes from the model, and thanks to plotly we just send it along and it shows up nicely.

add plot title

---

packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

With https://github.com/VEuPathDB/service-eda/pull/87, fixes the issue seen on QA with scatterplots.
Uses `options` to have apps tell the scatterplot viz not to request point Ids. Tested with the local backend on the above branch.

App scatterplots should not return point Ids

---

packages/libs/eda/src/lib/core/components/filter/HistogramFilter.tsx

This isn't a full fix, because let's say the binWidth is a reasonable `2.34` - the back end eventually suffers from "precision errors" and returns long decimal bin boundaries. The bin boundaries are what are selected as filter values when you "brush" a range across the histogram.
```
{
"histogram": [
{
"value": 0,
"binStart": "0.0",
"binEnd": "2.34",
"binLabel": "[0.0,2.34)"
},
{
"value": 0,
"binStart": "2.34",
"binEnd": "4.68",
"binLabel": "[2.34,4.68)"
},
{
"value": 0,
"binStart": "4.68",
"binEnd": "7.02",
"binLabel": "[4.68,7.02)"
},
{
"value": 0,
"binStart": "7.02",
"binEnd": "9.36",
"binLabel": "[7.02,9.36)"
},
{
"value": 0,
"binStart": "9.36",
"binEnd": "11.7",
"binLabel": "[9.36,11.7)"
},
{
"value": 0,
"binStart": "11.7",
"binEnd": "14.04",
"binLabel": "[11.7,14.04)"
},
{
"value": …
```

Another approach to fixing the long decimals in the histogram filter

---

packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.scss
packages/libs/user-datasets/src/lib/Components/UploadForm.tsx
packages/libs/web-common/src/App/UserMenu/UserMenu.jsx

Resolves #1359 
Adds places for users to input and edit any of the newest fields for their user datasets.
Note: Can't really submit because vdi isn't working yet. But can check using the test code i have in the PR (all marked as test)
To Dos:
Testing:
Since the VDI plugin isn't set up yet, I've just hardcoded some examples, and put a console.log so you can see that the appropriate fields are getting updated.

Add new fields to My user dataset page (AKA control page)

---

packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/storeModules/Record.js

Hi @dmfalke - would you mind taking a look at this?
We decided not to have a front end feature flag, but instead switch the feature on/off based on the availability of the back end Reporter.
I found a reasonably elegant way to disable the left hand navigation item. <s>Is the `return null` the only way to disable the actual section?</s> Both disabled by recordStoreModule upon loading.

Conditionally disable AI expression summary and nav menu item if no WDK reporter available

---

packages/libs/coreui/src/components/buttons/PopoverButton/PopoverButton.tsx
packages/libs/coreui/src/components/containers/Dimmable.tsx
packages/libs/coreui/src/components/containers/index.ts
packages/libs/coreui/src/components/inputs/SelectList.tsx
packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx
packages/libs/coreui/src/index.ts
packages/libs/wdk-client/src/Views/Records/RecordNotFoundPage.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/RecordTable_TaxonCounts_Filter.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Resolves https://github.com/VEuPathDB/web-monorepo/issues/1303
Resolves #1280
Resolves #1370 
<s>Implement dynamic Popover transition durations—enter fixed at 300 ms, exit set to Math.max(300, numSequences/10)—so that even with very large groups (e.g. 2.6 s for 26,000 sequences) the popover buttons go away cleanly without leaving behind ghost overlays that block the UI. (Main thread compute was disrupting the animation event processing. The extra animation time effectively waits for the compute to be done.) Groups <= 3,000 proteins won't see any UI behaviour differences at all.</s>
NEW APPROACH: figure out when the component `isFiltering` from `(realState !== volatileState)` and then do several things:
1. grey out the main table and overlay some LOADING text (our default `Loading` spinner …

Ortho ghost overlay fixes

---

packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.scss
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/GroupRecordClasses.GroupRecordClass.tsx

Fixes #1379 
Check out the video for the component at the top of the orthogroup table.
The highlighting is also there on the "taxon filter" on the main ortho "list of proteins" table.
https://github.com/user-attachments/assets/1e909326-c243-4741-9152-4bb68212c2aa

Make it easier to read the numbers from the phyletic distribution component

---

packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.scss

Oops I didn't realise the [old PR](https://github.com/VEuPathDB/web-monorepo/pull/1380) had been merged.
Addressing the feedback here: https://github.com/VEuPathDB/web-monorepo/pull/1380#issuecomment-2842102725
Not at all urgent - can go out any time at all!

Add extra padding to phyletic tree mouseover highlighting as per Ann's suggestion

---

packages/libs/eda/src/lib/core/components/filter/TableFilter.tsx
packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx

Fixes #1395 
Fixes #1306 
The paging bug was [reported in EDA](https://github.com/VEuPathDB/web-monorepo/issues/1306)
However it's also a problem in orthogroup pages:
- https://qa.orthomcl.org/orthomcl.b7_1/app/record/group/OG7_0000011#Sequences
- jump to page 2 and then search for `trsc`
Is there any paging on regular wdk RecordTables? Source code says no.

Make links searchable in tables, and sort out search on paged tables

---

packages/libs/coreui/src/components/buttons/SwissArmyButton/index.tsx
packages/libs/coreui/src/components/buttons/index.ts
packages/libs/web-common/src/config.ts
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.scss
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.tsx
packages/sites/genomics-site/webpack.config.local.mjs

Targets `ai-expression-cost-limit` at the moment!
The :+1: :-1: buttons are regular links to a Qualtrics survey with a couple of fields auto-filled from URL parameter values (hopefully!), but we can add client-side JavaScript too, if needed.
Wide browser:
Narrow browser:

AI expression - buttons for Was this helpful? 

---

packages/libs/wdk-client/src/Views/Records/RecordNavigation/RecordNavigationItem.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/record-page-new-feature.scss

Added badges to the navigation panel too
This required adding element IDs to the `<a>` elements which was straightforward.
I also investigated adding a badge to the unexpanded parent navigation item. I gave up on this for various reasons. The main one being that the `<li>` tree is dynamically rendered (not toggled with CSS visibility) so we don't know what children a list item has until it has been expanded. If we did know, it could all be done with CSS. But we don't!

Add BETA badge to the navigation menu too

---

packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/GroupStats.tsx

Image was a little squashed in one direction. I made it square and slightly bigger.
I also changed the layout to side-by-side unless narrow browser makes it wrap below.

Fix aspect ratio of new ortho help image and add flex-wrap layout

---

packages/libs/wdk-client/src/Components/Overlays/Dialog.tsx

In PR #1354 (“popup keyboard accessibility enhancements related to AI expression summary work”), we added keyboard-based dragging and bounds-checking—but uncovered a new issue: popups (e.g. the strategy step edit/revise popup) with content that renders or resizes after initial mount no longer stayed centered.
- In `handlePopupReady`, install a one-shot `ResizeObserver` on the popup node:
- Skip the observer’s very first callback (which always fires immediately).
- On the first *real* resize (e.g. data or images finish loading), recalculate `x` and `y` to center the popup.
- Disconnect the observer immediately to prevent further auto-centering.
- Use two flags—`hasMoved` and `hasAutoCentered`—to ensure:
1. We never auto-center *after* the user has manually moved the popup.
2. We only …

Fix: WDK popup auto-center on async content load

---

packages/libs/eda/src/lib/core/types/visualization.ts
packages/libs/eda/src/lib/notebook/ComputeNotebookCell.tsx
packages/libs/eda/src/lib/notebook/EdaNotebookAnalysis.tsx
packages/libs/eda/src/lib/notebook/NotebookCell.tsx
packages/libs/eda/src/lib/notebook/NotebookPresets.tsx
packages/libs/eda/src/lib/notebook/NotebookRoute.tsx
packages/libs/eda/src/lib/notebook/SubsettingNotebookCell.tsx
packages/libs/eda/src/lib/notebook/TextNotebookCell.tsx
packages/libs/eda/src/lib/notebook/VisualizationNotebookCell.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookParameter.tsx

Refactor to wire in the analysis state "from the source" (even though we don't have a proper question string-param to store the state in).
Also simplified the rendering/configuring process. We just render using the read-only preset structure as a guide. Computation and visualization IDs are provided in the preset template, and while rendering, the cell components just fetch the computation and/or visualization from analysisState as needed. We were lucky that there's a method that retrieves a visualization **and** computation using just the viz id.
As noted in comments somewhere, we can change it so that the notebook structure is dynamic/persisted state and can store further configuration (e.g. the text contents of an EditableTextCell)
To dos:

Eda notebook bm

---

packages/libs/eda/src/lib/notebook/ComputeNotebookCell.tsx
packages/libs/eda/src/lib/notebook/EdaNotebookAnalysis.tsx
packages/libs/eda/src/lib/notebook/NotebookCell.tsx
packages/libs/eda/src/lib/notebook/NotebookPresets.tsx
packages/libs/eda/src/lib/notebook/NotebookRoute.tsx
packages/libs/eda/src/lib/notebook/VisualizationNotebookCell.tsx
packages/libs/eda/src/lib/notebook/WdkParamNotebookCell.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookParameter.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookQuestionForm.tsx

There were a couple of issues and overengineered bits I have had a look at.
In both of the `useEffect` blocks in `EdaNotebookAnalysis` we’re doing things like
```
cell.wdkParameters = props.parameters;
cell.wdkUpdateParamValue = props.wdkUpdateParamValue;
```
but `presetNotebooks[...]` is an imported constant—modifying it directly means every consumer of that preset will see the change. That defeats the point of having a static “preset” and could lead to surprising cross-analysis/question state leaks.
Pass new `wdkState` alongside `analysisState` to all notebook cell components as the notebook tree is rendered. The `type == 'wdkparam'` notebook cell already knows the **names** of the parameters it is rendering (from its `paramNames` prop). All it needs is the richer information passed …

EDA-in-WDK notebook wdk param handling refactor

---

packages/libs/components/src/plots/BipartiteNetworkPlot.tsx
packages/libs/components/src/plots/NetworkPlot.css
packages/libs/components/src/plots/NetworkPlot.tsx
packages/libs/components/src/stories/plots/NetworkPlot.stories.tsx
packages/libs/eda/src/lib/core/components/computations/ComputationStepContainer.tsx
packages/libs/eda/src/lib/core/components/computations/RunComputeButton.tsx
packages/libs/eda/src/lib/core/components/computations/Types.ts
packages/libs/eda/src/lib/core/components/computations/plugins/Plugins.scss
packages/libs/eda/src/lib/core/components/computations/plugins/correlation.tsx
packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx
packages/libs/eda/src/lib/notebook/ComputeNotebookCell.tsx
packages/libs/eda/src/lib/notebook/EdaNotebook.scss
packages/libs/eda/src/lib/notebook/EdaNotebookAnalysis.tsx
packages/libs/eda/src/lib/notebook/NotebookCell.tsx
packages/libs/eda/src/lib/notebook/NotebookPresets.tsx
packages/libs/eda/src/lib/notebook/NotebookRoute.tsx
packages/libs/eda/src/lib/notebook/SubsettingNotebookCell.tsx
packages/libs/eda/src/lib/notebook/TextNotebookCell.tsx
packages/libs/eda/src/lib/notebook/Types.ts
packages/libs/eda/src/lib/notebook/VisualizationNotebookCell.tsx
packages/libs/eda/src/lib/notebook/WdkParamNotebookCell.tsx
packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookParameter.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookQuestionForm.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/pluginConfig.tsx

Resolves #1416 
This PR adds a few new props to components used in regular eda, so worth checking that still works just fine :) Specifically, ensure the mbio compute page looks normal. (I checked and it looks fine)
I tried out having the disabled cells closed by default. Then they open when they're ready. We'll see if folks like this.
I didn't remove the text cell. I think it can stay and just serve the new purpose of having extended help inside. I'm considering moving that correlation help into a text cell. Or possibly the bipartite network might want a bunch of help in a text cell... we'll see.

General eda notebook updates round 1

---

packages/libs/components/src/plots/PlotlyPlot.tsx

Fixes #1429
A more recent feature was overwriting any `annotations` produced by our plot components.

Patch the plot annotation regression

---

packages/libs/wdk-client/src/Components/Overlays/Dialog.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AiExpressionSummary.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/stepAnalysis/StepAnalysisWordCloudModal.tsx

Fixes #1446 
Changes Made:
- Dialog Component: Added allowKeyboardMoving prop (defaults to false) to make keyboard movement opt-in
- AiExpressionSummary: Opted into keyboard movement with allowKeyboardMoving={true}
- WordCloudModal: Opted into keyboard movement with allowKeyboardMoving={true}
Problem Solved:
- Login forms and other text inputs won't accidentally trigger keyboard movement when users type 'M'
- Components designed for keyboard movement still work by explicitly opting in
- Maintains backward compatibility for all existing Dialog usages

Add opt-in keyboard movement for Dialog components

---

packages/libs/web-common/src/App/UserMenu/UserMenu.scss
packages/libs/web-common/src/components/homepage/Header.scss
packages/libs/web-common/src/styles/breakpoints.scss

Changes
- Header Grid Layout: Fixed grid template columns specification - the previous `auto 1fr auto` was incorrectly defining only 3 columns when the grid template areas actually define 4 columns. Updated to `auto 1fr 0.3fr 0.1fr` for proper spacing distribution
- Responsive Breakpoints: Increased breakpoints to provide more breathing room (the horizontal nav menu has gained extra items since this was last looked at - **UserMenu was cropped off-screen at some window widths**):
- `$hamburger-width`: 1013px → 1160px
- `$cramped-header-width`: 1215px → 1300px
- User Menu Positioning:
- Simplified expanded state positioning by removing `margin-top: 6px` and adjusting `translateY` from -13px to -10px
- Added responsive positioning with `translateY(-2px)` for mobile screens to prevent the …

Fix header grid layout and improve user menu positioning across screen sizes

---

packages/libs/coreui/src/components/banners/Banner.tsx
packages/libs/coreui/src/components/buttons/FilledButton/index.tsx
packages/libs/coreui/src/components/theming/types.ts
packages/libs/coreui/src/stories/notifications/Banners.stories.tsx
packages/libs/eda/src/index.tsx
packages/libs/wdk-client/src/Views/User/Profile/UserProfile.tsx
packages/libs/web-common/src/components/Announcements.tsx
packages/libs/web-common/src/components/SubscriptionManagementBanner.jsx
packages/sites/clinepi-site/webapp/js/client/component-wrappers/Page.tsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx
packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/EdaNotebookParameter.tsx
packages/sites/mbio-site/webapp/wdkCustomization/js/client/component-wrappers/Page.tsx
packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/layout/OrthoMCLPage.tsx

So far i've just attacked the banner.
To make a long story short, we were halfway to creating the new banner (shown in figma mockups) when the first round of cuts happened. So we have these gorgeous mockups of banners, but hand't implemented them. This PR doesn't do all of the implementing (that should be branched from main), but adds enough for us to get rolling with the subscriptions stuff.
So far
- theme palettes should generally have warning, error, etc. colors defined, so i've added ours. This should have no effect anywhere other than the banner
- banner gets two options for call to action buttons. Primary (filled) and secondary (outlined). Both look nice with the close button :) 
One open question - currently, the banner uses specific levels (eg. 600) to set the border color and so …

Banner styling updates
