- .github/workflows/pr-check.yml
Once this is merged, I will add a branch protection rule to only allow PR merging if the action defined in this job is successful.
> add pr-check job

- .github/workflows/pr-check.yml
Testing out the cache option for github actinos. See https://github.com/actions/setup-node#caching-global-packages-data
**Edit** See the cache associated with this PR: https://github.com/VEuPathDB/web-monorepo/actions/caches
> Cache yarn operation

- packages/libs/eda/src/lib/workspace/AnalysisPanel.tsx
- packages/libs/eda/src/lib/workspace/EDAWorkspace.scss
- packages/libs/eda/src/lib/workspace/Subsetting/index.tsx
Closes https://github.com/VEuPathDB/web-eda/issues/1621
Note: I've chosen to only comment-out the code related to the global filters button in the event we want to keep it.
> Place filter chips above tabs and remove show all filters button

- packages/libs/wdk-client/src/StoreModules/UnhandledErrorStoreModule.ts
Resolves https://github.com/VEuPathDB/ApiCommonWebsite/issues/147
> Ignore alphafold 'empty textures' error

- packages/libs/wdk-client/src/Views/Answer/AnswerFilter.jsx
Resolves https://github.com/VEuPathDB/ApiCommonWebsite/issues/149
> Fix AnswerFilter bug by stopping propagation of click event

- packages/libs/web-common/src/routes.jsx
- packages/libs/web-common/src/styles/AllSites.scss
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx
This PR includes the following:
- Addssupport for `isFullscreen` RouteEntry prop to genomics-site
- Add CSS for standalone map
- Add missing prop for standalone map
> Add support to sites for standalone map

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx
Resolves https://redmine.apidb.org/issues/19659?project=true
> Link to dataset in internal gene tables

- packages/libs/study-data-access/src/shared/studies.ts
relates to https://github.com/VEuPathDB/service-dataset-download/issues/8
> Make `bulk_download_url` optional

- packages/libs/web-common/src/styles/default-layout.scss
Resolves #76 
Demo of this change:
https://user-images.githubusercontent.com/69446567/232606272-2ec64e5f-8be0-474c-8e90-67c52b22a89d.mov
> Adjust specificity to fix header breakpoint issue

- packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.jsx
- packages/sites/clinepi-site/webapp/js/client/component-wrappers/AnswerController.jsx
- packages/sites/clinepi-site/webapp/js/client/data/headerMenuItems.jsx
- packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/component-wrappers/index.js
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx
Resolves https://github.com/VEuPathDB/web-monorepo/issues/55 and resolves https://github.com/VEuPathDB/web-monorepo/issues/80
**NOTE:** the transparency is due to how I took the screenshot, so don't be alarmed by it!
> Remove 'User' from EDA references to UDs and improve sharing modal verbiage

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
Reference issue: https://github.com/VEuPathDB/web-eda/issues/1498
**Before**:
**After**:
https://user-images.githubusercontent.com/24446573/234331614-01bf9d55-4f98-4455-9f57-461d13cfa448.mp4
> 1498: add entity diagram to filter panel

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> Fix: ensure map legend title reflects selected variable in active marker configuration

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> Move legend to right edge and below pointer controls

- packages/libs/components/src/components/widgets/RadioButtonGroup.tsx
This will address https://github.com/VEuPathDB/web-monorepo/issues/183
> set default buttonColor to be primary

- packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
To reproduce the error:
1. Open the SAM
2. Click on Plots in the menu
3. Select a visualization type
> SAM: fix broken plots

- packages/libs/web-common/src/controllers/EdaMapController.tsx
This PR temporarily hardcodes the VEuPathDB logo for the SAM
> Hardcode veupathdb logo for SAM

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/AlphaFoldAttributeSection.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/main.js
This PR changes how the pdbe-molstar web component assets are loaded. Before, they were loaded on the initial page load, even if the user never visits a page using the web component. In this PR, they are loaded only when the web component is rendered.
> Defer loading pdbe-molstar assests until needed

- packages/libs/eda/src/lib/core/hooks/entityCounts.ts
This PR addresses an issue where requests to the count endpoint are done serially. This causes severe lag in the UI, especially when there is a large number of entities in the study.
> EDA: Make count requests in parallel

- packages/libs/eda/src/lib/core/types/study.ts
- packages/libs/eda/src/lib/map/analysis/utils/defaultOverlayConfig.ts
**Before**:
https://github.com/VEuPathDB/web-monorepo/assets/24446573/d9625b4e-2fb0-46da-9f18-2c893e4ec834
**After**: The legend loads with the correct data!
> Add type guards to prevent legend from disappearing

- packages/libs/study-data-access/src/study-access/components/UserTableDialog.tsx
> Update verbiage in access request denial popup

- packages/libs/eda/src/lib/core/utils/visualization.ts
No related issue. Just a bug fix.
> Fix infinite recursion when faceting

- packages/libs/components/src/map/ChartMarker.tsx
Fixes https://github.com/VEuPathDB/web-monorepo/issues/239
> Add default value for reduce()

- packages/libs/eda/src/lib/core/components/layouts/FloatingLayout.tsx
> Show plot controls in floating visualizations

- README.adoc
There was a little confusion recently about how to run the sites locally using this repo. This PR just adds some brief documentation to make the instructions more explicit.
> add details about running site locally to readme

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
This PR adds a check for geoconfigs in the `MapAnalysis` component. If none are found, then it renders an error message indicating as much:
It's not the prettiest thing, but I don't expect this to be an issue in production.
> Check that the current study has geoconfigs

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx
Show warning  text If the protein sequence has stop codons.
> 50735 prot seq warning

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
- packages/libs/eda/src/lib/map/analysis/hooks/standaloneMapMarkers.tsx
Follow up to https://github.com/VEuPathDB/web-monorepo/pull/292
There was a misunderstanding on my part about what was being requested in the comments, and I rushed the fix/merge.
> Clean up naming for better readability

- packages/sites/ortho-site/webapp/wdkCustomization/js/client/utils/dataSummary.tsx
This PR demonstrates how to add link attributes to the data summary table.
See related PR for model changes to include the new link attribute: https://github.com/VEuPathDB/OrthoMCLModel/pull/2
> Add link attribute to table

- packages/libs/components/src/map/SemanticMarkers.tsx
Fixes https://github.com/VEuPathDB/web-components/issues/352 again!
> Stop map markers occasionally disappearing at minimum zoom

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx
This removes restoring organism param values across searches
> Remove QuestionController wrapper

- packages/libs/wdk-client/src/Actions/BasketActions.ts
- packages/libs/wdk-client/src/Actions/DownloadFormActions.ts
- packages/libs/wdk-client/src/Actions/SummaryView/ResultTableSummaryViewActions.ts
- packages/libs/wdk-client/src/Controllers/DownloadFormController.tsx
- packages/libs/wdk-client/src/Controllers/ResultTableSummaryViewController.tsx
- packages/libs/wdk-client/src/Service/Mixins/BasketsService.ts
- packages/libs/wdk-client/src/Service/Mixins/SearchReportsService.ts
- packages/libs/wdk-client/src/Service/Mixins/StepsService.ts
- packages/libs/wdk-client/src/StoreModules/BasketStoreModule.ts
- packages/libs/wdk-client/src/StoreModules/DownloadFormStoreModule.ts
- packages/libs/wdk-client/src/StoreModules/ResultTableSummaryViewStoreModule.ts
- packages/libs/wdk-client/src/Views/ReporterForm/DownloadFormContainer.jsx
- packages/libs/wdk-client/src/Views/ResultTableSummaryView/BasketIconButton.tsx
- packages/libs/wdk-client/src/Views/ResultTableSummaryView/ResultTable.tsx
- packages/libs/wdk-client/src/Views/ResultTableSummaryView/ResultTableSummaryView.tsx
- packages/libs/wdk-client/src/Views/ResultTableSummaryView/Types.ts
- packages/libs/web-common/src/components/reporters/TranscriptAttributesReporterForm.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/ResultExportSelector.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/TranscriptRecordClasses.TranscriptRecordClass.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/TranscriptRecordClasses.TranscriptRecordClass.scss
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/gene-list-export-utils.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/util/transcriptFilters.js
closes #317 
This PR enables the UI for the `in_basket_filter` view filter.
**Screenshots**
> Enable UI for in_basket view filter

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/TranscriptRecordClasses.TranscriptRecordClass.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/gene-list-export-utils.tsx
This can be tested on https://dfalke-b.vectorbase.org
> Only request basket counts and display in_basket filter toggle for non-guest users

- packages/libs/wdk-client/src/Components/Mesa/Ui/DataCell.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.scss
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx
Fixes issues caused by recent changes:
1. Primary key links in step results not working.
2. InternalDataset page search buttons not lining up.
> Fix table rener issues

- packages/sites/clinepi-site/webapp/js/client/action-creators/AccessRequestActionCreators.js
- packages/sites/clinepi-site/webapp/js/client/controllers/AccessRequestController.jsx
- packages/sites/clinepi-site/webapp/js/client/controllers/AccessRequestController.scss
- packages/sites/clinepi-site/webapp/js/client/controllers/AccessRequestTextArea.jsx
- packages/sites/clinepi-site/webapp/js/client/controllers/AccessRequestView.jsx
- packages/sites/clinepi-site/webapp/js/client/selectors/AccessRequestSelectors.js
- packages/sites/clinepi-site/webapp/js/client/store-modules/AccessRequestStoreModule.js
> Wire up client to edit denied access requests

- packages/libs/multi-blast/src/lib/components/BlastWorkspaceResult.tsx
- packages/libs/multi-blast/src/lib/hooks/api.ts
See https://github.com/VEuPathDB/web-multi-blast/pull/24 for details
> Apply changes from https://github.com/VEuPathDB/web-multi-blast/pull/24

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
- packages/libs/eda/src/lib/map/analysis/MapHeader.tsx
- packages/libs/eda/src/lib/map/analysis/MapSideNavigation.tsx
- packages/libs/eda/src/lib/map/analysis/MapSidePanel.tsx
- packages/libs/eda/src/lib/map/analysis/MapVizManagement.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/MapTypeConfigurationMenu.tsx
- packages/libs/eda/src/lib/map/analysis/Types.ts
- packages/libs/eda/src/lib/map/index.ts
Related to #241
This PR contains preliminary work to add the collections map type to the eda map.
Changes include:
- Variable renaming
- Modifications to finding active menu item and active map type
- Extracting some components
_Note that this PR is targeting the branch `map-collection-variable-map-type`, rather than `main`. The intent is to allow for incremental PR merges for #241. We'll see how that goes._
> Restructure side menu to allow for subheadings.

- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/BubbleMarker.tsx
> updated bubble marker

- packages/libs/wdk-client/src/Utils/UserPreferencesUtils.ts
This PR addresses an issue where step results will not load if user preference and/or step details includes an unknown attribute.
This would be done by removing the unknown attributes from user prefs and step details.
If we don't fix it, we will get repeated error logs. On the other hand, if the attribute was mistakenly removed from the model, then the user will see the column in their results again, when it is added back.
If we do fix it, we will only get one error log per step, but the column will not reappear if it is added back to the model.
Thoughts?
> Filter out unknown attributes from user pref and step details

- packages/libs/eda/src/lib/map/analysis/DraggableVisualization.tsx
- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
- packages/libs/eda/src/lib/map/analysis/MapVizManagement.tsx
- packages/libs/eda/src/lib/map/analysis/appState.ts
Move active viz to realm of map type config, and clean up some labels and ids.
> Some additional clean-up

- packages/libs/wdk-client/src/Utils/ComponentUtils.tsx
> Add check for HTML entities in safeHtml util

- packages/libs/eda/src/lib/map/analysis/utils/defaultOverlayConfig.ts
Closes https://github.com/VEuPathDB/web-monorepo/issues/416
> Selected all numerator values by default in bubble config

- .github/workflows/pr-check.yml
- packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
- packages/sites/clinepi-site/package.json
- packages/sites/genomics-site/package.json
- packages/sites/mbio-site/package.json
- packages/sites/ortho-site/package.json
- yarn.lock
fixes #435 
Revert changes made to yarn.lock in e9f44779e7b0 and rerun `yarn install`.
This was done by running these commands:
```
git co e9f44779e7b0~1 -- yarn.lock
yarn install
```
> Re-resolve package versions re custom visx package

- packages/libs/http-utils/src/FetchClient.ts
> Reword error message

- packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
Resolves #441 
Adds a primary theme role for the swap button in diff abund. Hopefully not too taxing to review!
> add primary theme color to swap button

- packages/libs/eda/src/lib/core/hooks/study.ts
> Request study_access attribute

- packages/libs/eda/src/lib/workspace/AllAnalyses.tsx
> Fix My Analyses context error

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx
> show LOPITtryp table on gene pages -refs #49617

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx
- Fix placement of beta icon
- Open in new tab
> Fix map menu entry

- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BubbleMarkerConfigurationMenu.tsx
> Just disable dates for bubbles

- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/BarPlotMarkerIcon.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/BarPlotMarkersIcon.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/BubbleMarkerIcon.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/DonutMarkerIcon.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/DonutMarkersIcon.tsx
- packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/icons/index.ts
> Rename marker icons to differentiate from marker components

- packages/libs/http-utils/src/FetchClient.ts
(cherry picked from commit 81b3dae3a2170c67e58d936457e4da66160475a1)
> Remove initial new line from error message (#520)

- packages/libs/components/src/plots/VolcanoPlot.tsx
- packages/libs/components/src/stories/plots/VolcanoPlot.stories.tsx
- packages/libs/components/src/stories/plots/VolcanoPlotRef.stories.tsx
- packages/libs/components/src/types/plots/volcanoplot.ts
- packages/libs/eda/src/lib/core/api/DataClient/types.ts
- packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/differentialabundance.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx
- packages/libs/eda/src/lib/core/components/visualizations/options/types.ts
- packages/libs/eda/src/lib/core/types/study.ts
- packages/libs/eda/src/lib/core/types/variable.ts
- packages/libs/eda/src/lib/core/utils/study-metadata.ts
this turned into more than i thought it would be... the idea was to add a new input for the diff abund compute, to support choosing a method explicitly. backend that meant what i thought was a minor api change, which was something less minor here than i had assumed. so ive gone and basically added more explicit support for variable collections as well.
Still need to make the new method input prettier and have the available method differ by the collection chosen. im considering leaving the available methods unconstrained for the time being, until some backend work is done to better support that.
> Maaslin method for diff abund

- packages/sites/genomics-site/webapp/wdkCustomization/css/client.scss
this is a one line change.  i've made 3 lines of comments and messages
> no display of junction_record pk

- packages/libs/components/src/components/plotControls/EzTimeFilter.tsx
- packages/libs/eda/src/lib/map/analysis/EZTimeFilter.tsx
> Timeslider help icon and further slimming

- packages/libs/components/src/map/SemanticMarkers.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BubbleMarkerMapType.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
Fixes #575 
But it looks like that won't get closed automatically because this doesn't merge to main?
> Possible fix for reset/flyTo all data; fix animation other worlds bug

- packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.scss
https://redmine.apidb.org/issues/51845
> group record page, proteins table, increase space before checkbox

- packages/libs/eda/src/lib/workspace/AnalysisPanel.tsx
This PR adds a beta icon the SAM link in the EDA workspace.
> Add a beta icon to the SAM link in EDA.

- packages/libs/eda/src/index.tsx
- packages/libs/eda/src/lib/workspace/AllAnalyses.tsx
- packages/libs/eda/src/lib/workspace/PublicAnalyses.tsx
- packages/libs/eda/src/lib/workspace/PublicAnalysesRoute.tsx
- packages/libs/eda/src/lib/workspace/WorkspaceRouter.tsx
- packages/libs/web-common/src/App/Home/Home.jsx
- packages/libs/web-common/src/App/Showcase/Showcase.jsx
- packages/libs/web-common/src/config.ts
- packages/libs/web-common/src/routes.jsx
- packages/sites/clinepi-site/webapp/js/client/data/homeContent.js
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/routes.jsx
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/component-wrappers/index.js
- Support list of example analysis author IDs, and use it for homepage (mbio and clinepi)
- Fix webapp url path segments for portal download page
Note, conifer will need to be updated with the latest list of authors
> Last minute b66 updates

- packages/libs/web-common/src/components/Announcements.jsx
Co-authored-by: Dave Falke <dfalke@uga.edu>
(cherry picked from commit 3f3496563e56ce3fabc7154570a3fa1f23f437dc)
> fix species in vb banners (#690)

- packages/libs/web-common/src/App/Home/Home.jsx
- packages/libs/web-common/src/App/Showcase/Showcase.jsx
This code was removed under the impression that it wasn't used.
> Add back code supporting link on cards

- packages/libs/web-common/src/App/Home/Home.jsx
- packages/libs/web-common/src/App/Showcase/Showcase.jsx
(cherry picked from commit ea18d346f694d6546fc3a1d2c11db7d81e86bc43)
> Add back code supporting link on cards (#700)

- packages/libs/eda/src/lib/map/analysis/MapFloatingErrorDiv.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/BarMarkerMapType.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/plugins/DonutMarkerMapType.tsx
- packages/libs/eda/src/lib/map/analysis/mapTypes/shared.ts
- packages/libs/eda/src/lib/map/analysis/mapTypes/shared.tsx
Fixes #708
Fixes #713 
See #708 for use cases that were broken.
> Improve map error handling and fix some logic related to marker config and legend updates

- packages/libs/user-datasets/src/lib/Components/UserDatasetsWorkspace.tsx
Fixes https://github.com/VEuPathDB/web-monorepo/issues/569
> Wrap and style error message

- packages/libs/components/src/plots/BipartiteNetwork.css
- packages/libs/components/src/plots/BipartiteNetwork.tsx
- packages/libs/components/src/stories/plots/BipartiteNetwork.stories.tsx
- packages/libs/components/src/types/plots/network.ts
- packages/libs/eda/src/lib/core/api/DataClient/types.ts
depends on https://github.com/VEuPathDB/EdaDataService/pull/347
> Network partitions api update

- packages/libs/components/src/map/MapVEuMap.tsx
- packages/libs/eda/src/lib/core/utils/visualization.ts
Closes https://github.com/VEuPathDB/web-monorepo/issues/763
> Add more gradations to map zoom

- packages/libs/components/src/components/widgets/Notification.tsx
This will address https://github.com/VEuPathDB/web-components/issues/435. 
Super easy fix 😅
> capitalize text, Ok

- packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
This will resolve https://github.com/VEuPathDB/web-monorepo/issues/265. 
It is obvious what to do, though I could not find where the plot subtitles are displayed 😅
> change plot subtitles for Ranked abundance

- packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
- packages/libs/eda/src/lib/core/types/utility.ts
This will address https://github.com/VEuPathDB/web-eda/issues/1488.
It would be great if you can review and make any suggestions, if necessary, @dmfalke 👍
> typing any for Scatterplot and Lineplot Vizs

- packages/libs/multi-blast/src/lib/components/ReportSelect.tsx
> Fix zIndex issue w/ ReportSelect in mblast

- packages/libs/eda/src/lib/core/components/visualizations/Visualizations.scss
- packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
> Fix css issue w/ viz preview containers

- packages/libs/eda/src/lib/core/components/computations/plugins/Plugins.scss
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
Partially resolves #771 
Adds expandable section info to the two correlation apps.
https://github.com/VEuPathDB/web-monorepo/assets/11710234/95b7a972-42da-421a-9a54-78df7c148869
Not much else to say!
> Feature 771 expandy section apps

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/controllers/FastaConfigController.tsx
Addresses cases where not all searches are defined in the model, as is the case in VectorBase.
> Ignore searches that are not defined in the model

- packages/libs/eda/src/lib/map/analysis/SubStudies.tsx
- packages/libs/eda/src/lib/map/analysis/TimeSliderQuickFilter.tsx
> Overhaul of timeslider verbiage

- packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
Fixes #833
See https://github.com/VEuPathDB/web-monorepo/issues/833#issuecomment-1946211463 for diagnosis and cure.
> Re-enable "Full" mode for lineplot y-axis

- packages/libs/wdk-client/src/StoreModules/QuestionStoreModule.ts
This PR addresses a race condition that happens on the SRT page, when switching between tabs rapidly.
> Check that paramUIState is defined

- packages/libs/components/src/plots/VolcanoPlot.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/VolcanoPlotVisualization.tsx
Closes https://github.com/VEuPathDB/web-monorepo/issues/808
Most of the diff is just indentation!
> Add message for no data in volcano plot

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/routes.jsx
The new srt isn't working in the portal
> Use old srt for portal

- packages/libs/wdk-client/src/Views/Question/Params/FilterParamNew/FilterParamObserver.ts
(cherry picked from commit 2c8f4402caf91723fb145a9373a423fb2c94fd69)
> Clear errorMessage when a new ontology summary is loaded (#889)

- packages/libs/eda/src/lib/core/components/computations/plugins/Plugins.scss
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
Resolves #843 
Screenshot of the change:
> Display fixed dummy input in correlation config UI for UX reasons

- packages/libs/multi-blast/src/lib/components/ReportSelect.tsx
- packages/libs/multi-blast/src/lib/hooks/api.ts
- packages/libs/multi-blast/src/lib/utils/api.ts
- packages/libs/multi-blast/src/setupProxy.js
- packages/libs/user-datasets/src/lib/Service/UserDatasetUploadWrappers.ts
This PR adds missing bearer token support. It also removes an outdated authentication method for local dev in multi-blast.
> Missing bearer token support

- packages/libs/eda/src/lib/core/components/computations/plugins/abundance.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/alphaDiv.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/betadiv.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayAssay.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
Resolves https://github.com/VEuPathDB/web-eda/issues/1579
> Refactor computation method options to include displayName property

- packages/libs/user-datasets/src/lib/Components/UploadForm.tsx
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetNewUploadController.tsx
- packages/libs/user-datasets/src/lib/Utils/types.ts
- packages/libs/user-datasets/src/lib/Utils/upload-config.tsx
- packages/libs/wdk-client/src/Components/InputControls/FileInput.tsx
- packages/libs/wdk-client/src/Utils/Converters.ts
* Add support for max file size
* formatting
* verbiage
(cherry picked from commit 1e22d36b30deb894e67844ef0d08585a7f2bde77)
> Add support for max file size (#922)

- packages/libs/components/src/map/MapVEuMap.tsx
- packages/libs/eda/src/lib/map/analysis/DraggableLegendPanel.tsx
- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
This will address https://github.com/VEuPathDB/web-monorepo/issues/199. Screenshots are:
> adding layers for SAM

- packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
> Lineplot - don't attempt series reordering for integer ordinals

- packages/libs/wdk-client/src/Views/Question/Params/TreeBoxEnumParam.tsx
fixes https://redmine.apidb.org/issues/53964
> fix condition for testing isMultiPick

- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/genomeSummaryView/GenomeSummaryView.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/genomeSummaryView/ResultsTable.tsx
Resolves https://redmine.apidb.org/issues/53775
Filter unchecked:
Filter checked:
> Fix 'Show empty chromosomes' filter bug

- packages/libs/web-common/src/App/NewsSidebar/News.jsx
Resolves https://redmine.apidb.org/issues/46994
> Fix HTML rendering issue in news headlines

- packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/OrthoDataTable.tsx
- packages/sites/ortho-site/webapp/wdkCustomization/js/client/controllers/ProteomeSummaryController.scss
Resolves https://redmine.apidb.org/issues/54007
No filtering:
Filtering by search:
> Add row counts to ortho species table

- packages/libs/wdk-client/src/Views/Question/DefaultQuestionForm.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/questions/InternalGeneDataset.tsx
Resolves https://redmine.apidb.org/issues/53773
> Add beta icon to WGCNA search

- packages/libs/user-datasets/src/lib/Utils/upload-config.tsx
- packages/libs/web-common/package.json
- packages/libs/web-common/src/hooks/diyStudySummaries.tsx
- packages/sites/clinepi-site/package.json
- packages/sites/clinepi-site/webapp/js/client/controllers/UserDatasetRouter.tsx
- packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
- packages/sites/clinepi-site/webapp/js/client/wrapStoreModules.js
- packages/sites/clinepi-site/webapp/js/client/wrapWdkService.ts
- packages/sites/mbio-site/package.json
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/controllers/UserDatasetRouter.ts
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/wrapStoreModules.js
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/wrapWdkService.ts
- yarn.lock
I rebuilt my dev sites with this branch, but my clinepi and mbio dev sites don't have the apache config for vdi, yet:
https://dfalke-b.clinepidb.org
https://dfalke-b.microbiomedb.org
> Use vdi for all sites

- packages/libs/user-datasets/src/lib/Utils/upload-config.tsx
> Add filesize limit for biom files

- packages/libs/eda/src/lib/workspace/EDAWorkspaceHeading.tsx
> Only show Management Dashboard button for user datasets

- packages/libs/eda/src/lib/core/hooks/study.ts
- packages/sites/clinepi-site/webapp/js/client/routes/userDatasetRoutes.tsx
- packages/sites/mbio-site/webapp/wdkCustomization/js/client/routes/userDatasetRoutes.tsx
This PR fixes the keys used for configuring user dataset detail views. 
It also makes an error message clearer.
> Vdi fix detail type keys

- packages/libs/user-datasets/src/lib/Components/UploadForm.tsx
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetNewUploadController.tsx
- packages/libs/user-datasets/src/lib/Service/api.ts
> Handle user dataset upload errors

- packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
- packages/libs/user-datasets/src/lib/Components/UserDatasetStatus.tsx
> Simplify compatibility messaging in dataset details page

- packages/libs/eda/src/lib/workspace/EDAWorkspaceHeading.tsx
- packages/libs/study-data-access/src/study-access/permission.ts
> EDA access management button update

- packages/libs/eda/src/lib/core/utils/visualization.ts
Closes https://github.com/VEuPathDB/web-monorepo/issues/895
> Improve zoom to geohash level mapping

- packages/libs/user-datasets/src/lib/Components/UserDatasetStatus.tsx
Resolves https://github.com/VEuPathDB/EdaNewIssues/issues/776
> Fix tooltip issue with status icon

- packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
- packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This will address https://github.com/VEuPathDB/web-monorepo/issues/1044.
A screenshot is attached here:
> set default floating plot color as dark gray

- packages/libs/eda/src/index.tsx
The simple dev server wasn't starting!
> Fixed missing `sharingUrlPrefix`

- packages/libs/components/src/map/SemanticMarkers.tsx
This will address https://github.com/VEuPathDB/web-monorepo/issues/1054.
> tweak marker selection snackbar messages

- packages/libs/eda/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
Fixes #1064 
@dmfalke was spot on about the missing dependency!
> added missing dep

- packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
Resolves issue [described in this Slack thread](https://epvb.slack.com/archives/GBDR4LDNC/p1714580392833699).
> Fix datasetType casing in switch statement

- packages/libs/study-data-access/src/study-access/components/StudyAccess.tsx
> Enable HTML in study access dashboard's title

- packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
Resolves https://epvb.slack.com/archives/C01DS6HBY3Z/p1715270392560699
> Fix regression in RecordTable search filter

- packages/libs/user-datasets/src/lib/Actions/UserDatasetsActions.ts
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
Fixes #1116
This PR handles 404 responses for the user dataset detail page.
> Userdataset load error

- packages/libs/web-common/src/components/Announcements.jsx
> Add banner related to fixing variable identifiers in mbio

- packages/libs/eda/src/lib/core/components/FilterChipList.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/correlation.tsx
- packages/libs/eda/src/lib/core/components/computations/plugins/correlationAssayMetadata.tsx
- packages/libs/web-common/src/components/Announcements.jsx
This PR includes some cherry-picks from `main`
> v1.0.153 patch.3

- packages/libs/components/src/components/plotControls/MultiSelect.tsx
- packages/libs/components/src/plots/NetworkPlot.tsx
This will possibly address https://github.com/VEuPathDB/web-monorepo/issues/1127. A video capture with storybook is included in the following:
https://github.com/VEuPathDB/web-monorepo/assets/12802305/727c492a-b65c-483a-bfd3-51c9fc875f32
> network node clicking events

- packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx
Fixes #1142 
Has not been widely consulted!
Before:
After:
> Filter out unimplemented viz for new viz picker (single app mode)

- packages/libs/eda/src/lib/workspace/DownloadTab/index.tsx
Fixes #1146
There was a bug in the logic used for showing the loading indicator. This PR fixes that.
> Refine logic for download file listing status

- packages/libs/coreui/src/components/containers/Modal.tsx
- packages/libs/coreui/src/components/inputs/SingleSelect.tsx
- packages/libs/eda/src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
- packages/libs/user-datasets/src/lib/Actions/UserDatasetsActions.ts
- packages/libs/user-datasets/src/lib/Components/Detail/UserDatasetDetail.jsx
- packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
- packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetCommunityModal.jsx
- packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.jsx
- packages/libs/user-datasets/src/lib/Components/Sharing/UserDatasetSharingModal.scss
- packages/libs/user-datasets/src/lib/Components/ThemedDeleteButton.tsx
- packages/libs/user-datasets/src/lib/Components/ThemedGrantAccessButton.tsx
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetListController.tsx
- packages/libs/user-datasets/src/lib/Service/api.ts
- packages/libs/user-datasets/src/lib/StoreModules/UserDatasetDetailStoreModule.ts
- packages/libs/user-datasets/src/lib/StoreModules/UserDatasetListStoreModule.ts
Fixes #1141
Changed include:
- Add community modal state to Redux store
- Dropdown button to choose between community and individual
- Use coreui modal
- Tweak verbiage
> User datasets community sharing updates

- packages/libs/components/src/plots/NetworkPlot.css
- packages/libs/eda/src/lib/core/components/visualizations/implementations/BipartiteNetworkVisualization.tsx
@asizemore This will address https://github.com/VEuPathDB/web-monorepo/issues/1153. A screenshot is attached here:
> fixing the issues of plot box and node labels

- packages/libs/wdk-client/src/Actions/UserActions.ts
- packages/libs/wdk-client/src/Service/ValidationBundle.ts
- packages/libs/wdk-client/src/Utils/Errors.ts
- packages/libs/wdk-client/src/Utils/Json.ts
This PR introduces better handling for `ValidationBundle` errors to `wdk-client`.
> Handle Wdk ValidationBundle error

- packages/libs/eda/src/lib/core/hooks/promise.ts
- packages/libs/eda/src/lib/core/hooks/state.ts
- packages/libs/eda/src/lib/workspace/AllAnalyses.tsx
- packages/libs/eda/src/lib/workspace/Subsetting/index.tsx
- packages/libs/user-datasets/src/lib/Controllers/UserDatasetDetailController.tsx
This PR fixes some issue when guest users interact with community vdi datasets:
- Forbidden network response error
- Runtime reference error
- In EDA, the wrong default variable can be selected when switching studies. In addition to fixing this bug, the UI now includes the variable tree when this happens, allowing the user to select a valid variable.
_The prod branch will also get these changes._
> VDI: fix guest errors with community datasets

- packages/libs/wdk-client/src/Controllers/RecordController.tsx
- packages/libs/wdk-client/src/StoreModules/RecordStoreModule.ts
- packages/libs/wdk-client/src/Utils/CategoryUtils.tsx
- packages/libs/wdk-client/src/Views/Records/RecordUtils.ts
See https://github.com/VEuPathDB/OrthoMCLModel/commit/23305fb7457254d80c05198a6c346d9a24ce3e41 where an example configuration change has been made on the `diamond` branch.
Here we handle it on the client side.
To do:
> Add new WDK record scope: record-collapsed

- packages/libs/coreui/src/components/Mesa/style/Ui/DataTable.scss
- packages/libs/web-common/src/App/Header/Header.scss
- packages/libs/web-common/src/styles/AllSites.scss
This PR fixes an issue with stick table headers on genomic sites.
> Fix z-index rules related to sticky table headers

- packages/libs/eda/src/lib/map/MapVeuContainer.tsx
- packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
- packages/libs/wdk-client/src/Components/Layout/Page.tsx
- packages/libs/wdk-client/src/Core/Root.tsx
- packages/libs/wdk-client/src/Core/routes.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/controllers/GenomicsIndexController.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/controllers/IndexController.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/routes.jsx
This PR uses the homepage as a backdrop when the "login required" modal is displayed.
> Genomics login modal with homepage as backdrop

- packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx
- packages/libs/user-datasets/src/lib/Components/Detail/BigwigDatasetDetail.jsx
- packages/libs/web-common/src/user-dataset-upload-config.tsx
- Close SelectTree popover when a selection is made
- Make SelectTree popover div smaller
- Update verbiage at bottom of upload forms
> User dataset tweaks

- packages/libs/web-common/src/user-dataset-upload-config.tsx
> Update display name for existing rna-seq user dataset type

- packages/libs/web-common/src/config.ts
- packages/libs/web-common/src/user-dataset-upload-config.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/userDatasetRoutes.tsx
- packages/sites/genomics-site/webpack.config.local.mjs
This PR adds the following:
- Allow the user dataset upload forms offered to be configurable
- Update verbiage for rnaseq upload form
- Use consistent capitalization for bigWig
> User datasets verbiage and config

- packages/libs/coreui/src/components/buttons/PopoverButton/PopoverButton.tsx
- packages/libs/coreui/src/components/theming/UIThemeProvider.tsx
> Keyboard a11y improvements  focus visible

- packages/libs/wdk-client/src/StoreModules/RecordStoreModule.ts
- packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTableSection.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/records/GeneRecordClasses.GeneRecordClass.jsx
> Prevent partial table state updates for record page

- packages/libs/web-common/src/styles/client.scss
addresses https://github.com/VEuPathDB/web-monorepo/issues/1319
> dont wrap sentence

- packages/libs/eda/src/lib/core/components/variableSelectors/VariableTree.tsx
- packages/libs/eda/src/lib/core/utils/study-metadata.ts
Only order entities alphabetically in the variable tree components.
> only order variable tree entities alphabetically

- packages/libs/components/src/stories/colormaps/Categorical.stories.tsx
- packages/libs/components/src/stories/plots/ScatterPlot.stories.tsx
- packages/libs/components/src/stories/plots/ScatterPlot.storyData.ts
- packages/libs/components/src/types/general.ts
- packages/libs/eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
- packages/libs/web-common/package.json
- packages/libs/web-common/src/components/eda/EdaScatterPlot.tsx
- yarn.lock
Resolves #1360 
This is not the best fix ever, but will somewhat scalable. At least we won't need to update it until we have some more use cases to think about.
All the highlighting information was getting a bit unwieldy so I added a new type `HighlightedPointsDetails`. This modification is responsible for most of the changes.
@bobular I couldn't install the pluralize package so that we can have better (real) pluralization. Do you have the authority to do so?
> Update for the phenotype graph legend.

- packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx
> Fix logic for showing spinner when tree is not fetched on purpose

- packages/libs/user-datasets/src/lib/Components/List/UserDatasetList.tsx
- packages/libs/user-datasets/src/lib/Utils/types.ts
> Made summary optional for user datasets list

- packages/libs/eda/src/lib/core/utils/default-axis-range.ts
> Fix user dataset subsetting distribution OOM

- packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
stuart requested especifically for the group stats table
https://orthomcl.org/orthomcl/app/record/group/OG7_0003896#GroupStat
https://aurreco-n.orthomcl.org/orthomcl.root/app/record/group/OG7_0003896#GroupStat
> do not show search or count for 2-row tables

- packages/libs/wdk-client/src/Views/Records/RecordTable/RecordTable.jsx
Wouldn't have happened in a TypeScript file!
> Make table search null-safe

- .gitignore
These files can differ from user to user and shouldn't be tracked. Though we should think of a strategy for shared AI context. Especially for large codebases where we don't need to redo heavy AI for each user.
Out of interest, Claude Code did an OK job deciphering the monorepo structure and was able to find source files of interest for me.
> Ignore claude file

- packages/libs/web-common/src/components/Announcements.tsx
- packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/userComments/UserCommentForm/PubmedIdField.tsx
There won't be anything major in this PR. Just verbiage and the like.
The URL change is optional/cosmetic. It's probably only worth releasing along with more urgent issues or typos.
> Last minute tweaks for Liverpool AI linking
